window.notebookStylesData = [
    {
        "id": "style-01",
        "tag": "活力數位",
        "name": "💥 數位普普風格 (Digital Pop)",
        "description": "採用有機形狀與高彩度配色，消除科技冰冷感，極具社群親和力。",
        "applicable": "年輕族群行銷提案、創意發想會議、新創募資簡報、教育培訓",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：數位普普風格 (Digital Pop)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Digital Pop Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    organic_shapes: true\n    avoid_perfect_shapes: \"嚴禁使用完美的正方形、長方形或正圓形色塊\"\n    key_elements: [\"變形蟲（Amoeba）\", \"不規則雲朵\", \"帶有微小手繪抖動感（Hand-drawn Jittery）的粗線條\"]\n  styling:\n    border_rules: \"所有文字框、圖片容器與卡片邊緣，必須加上 2px - 3px 的粗黑色實線邊框\"\n    shadow_effect: \"啟用重影黑影（Hard Drop Shadows），使視覺元件呈現如同復古貼紙堆疊的物理感\"\n    vibes: \"模擬 Instagram 限時動態、手寫便利貼（Post-it）與拼貼塗鴉，營造親切、不妥協、活力充沛的氛圍\"\n  color_palette:\n    primary: \"高彩度糖果色 (High-Chroma Candy Colors)\"\n    accent: \"螢光黃 (Fluorescent Yellow)、酸橙綠 (Lime Green)\"\n    neutral: \"米白底色搭配碳黑框線，拒絕死板純白\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"長篇大論\", \"學術官腔\", \"冰冷硬直的數據羅列\"]\n  writing_style: \"口語化、具高度煽動力與情緒渲染力的對話感。句首與關鍵處必須適度穿插 Emoji（例如：💥, 🎨, 🚀, 👀）\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 痛點大吐槽：用幽默好笑的例子切入目前市面上的不合理現狀\"\n    - \"2. 創意點子大爆發：一頁展示一個顛覆傳統的瘋狂好點子\"\n    - \"3. 成果與未來願景：用高彩度圖形模組展示我們對未來的想像\"\n    - \"4. 行動呼籲：給觀眾一個極具社群感的 Call to Action（CTA）\""
    },
    {
        "id": "style-02",
        "tag": "活力數位",
        "name": "⚡ 運動能量風格 (Sports Energy)",
        "description": "利用傾斜幾何與強烈高能對比色，創造極致的速度感與視覺張力。",
        "applicable": "業務團隊目標大會、競爭對手分析、健身/遊戲/科技新品提案",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：運動能量風格 (Sports Energy)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Sports Energy Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    dynamic_shapes: true\n    tilted_angle: \"所有色塊、圖片容器與裝飾元素必須強制右傾斜 15 度，或使用平行四邊形（Parallelogram）\"\n    split_lines: \"使用粗獷、銳利的斜向分割線（Slashed Cuts）來區分各個資訊欄位\"\n  styling:\n    motion_blur: \"背景與點綴條紋需呈現動態條紋感，引導觀眾視線向前延伸\"\n    vibes: \"運動跑道、賽車場上的瞬息萬變，強烈激發團隊成員的戰鬥力與危機意識\"\n  color_palette:\n    primary: \"極速黃 (Speed Yellow)、火焰橙 (Blaze Orange)\"\n    background: \"碳黑 (Carbon Black) 或 深邃灰 (Deep Charcoal)，營造暗色系的高級競技感\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"被動句式\", \"冗長鋪陳\", \"委婉推託之詞\"]\n  writing_style: \"高能量、爆發式文案。大量使用高強度、指向明確的主動動詞（例如：擊碎、突破、超越、碾壓、狂飆）。避免多餘的助詞\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 危機/目標宣告：指出不得不突破的燃眉之急與絕對死線\"\n    - \"2. 戰術解鎖：一頁一戰術，以強烈的傾斜卡片展示核心突圍手段\"\n    - \"3. 競爭力對決：使用高對比雙欄，一針見血對抗主要競爭對手\"\n    - \"4. 全力衝刺：終極目標數據的具象化，號召團隊全員全速前進\""
    },
    {
        "id": "style-03",
        "tag": "活力數位",
        "name": "🏛️ 古典普普風格 (Classical Pop)",
        "description": "將希臘羅馬古典藝術與現代消費符號強制碰撞，形成高記憶點的違和趣味。",
        "applicable": "廣告創意提案、Z 世代趨勢報告、新舊融合主題、尾牙/競賽開場",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：古典普普風格 (Classical Pop)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Classical Pop Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    collage_style: \"極限違和感拼貼 (Anachronistic Collage)\"\n    visual_clash: \"將莊嚴優雅的希臘羅馬大理石雕像、文藝復興名畫，強行搭配現代叛逆消費符號（如：墨鏡、泡泡糖、玩自拍、喝汽水）\"\n  styling:\n    background_patterns: \"使用半調網點（Halftone Dots）或孟菲斯（Memphis）幾何圖案作為點綴底紋\"\n    vibes: \"藝術感與荒謬惡搞並存，利用高級藝術與街頭文化的強烈反差，營造過目難忘的視覺幽默與前衛美感\"\n  color_palette:\n    primary: \"古典大理石灰 (Statue Grey)\"\n    accent: \"螢光桃紅 (Shocking Pink)、酸性藍 (Acid Blue)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"死板的純技術說明\", \"照本宣科的簡報\"]\n  writing_style: \"『一本正經地講幹話』。標題必須顯得極為莊嚴宏大、富含歷史感；但內文與數據說明卻要直白、辛辣、富含 Z 世代的自嘲與幽默\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 古老包袱：列出傳統思維中沉重、令人昏昏欲睡的古板現狀\"\n    - \"2. 荒謬吐槽：揭露當前痛點在現代人眼中有多麼荒謬可笑\"\n    - \"3. 顛覆性創新解法：將新技術/新創意包裝為『新古典啟蒙』展示\"\n    - \"4. 破圈宣言：呼籲大膽打破框架，跨界狂歡\""
    },
    {
        "id": "style-04",
        "tag": "文青質感",
        "name": "📖 現代雜誌風格 (Modern Magazine)",
        "description": "模擬高級生活雜誌排版，捨棄一切多餘邊框，以高雅留白與精美比例取勝。",
        "applicable": "品牌形象手冊、香氛家居行銷企劃、人資文化手冊、藝術展覽導覽",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：現代雜誌風格 (Modern Magazine)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Modern Magazine Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    layout_type: \"極簡無邊框 (Editorial Sans-Border)\"\n    whitespace_ratio: \"幻燈片四周保留至少 15%-20% 的『呼吸留白』，嚴禁使用任何實線邊框或明顯的表格隔線\"\n  styling:\n    typography_contrast: \"完全依靠超大字體（模擬雜誌頭條）與極小註解文字的強烈比例對比，來引導閱讀視線\"\n    vibes: \"散發類似《Vogue》、《Kinfolk》或《Cereal》的高端實體印刷品氛圍，強調高級感、慢步調、從容不迫\"\n  color_palette:\n    background: \"暖乳白色 (Warm Milk)、純淨燕麥色 (Oatmeal)\"\n    primary: \"深炭灰 (Charcoal Black)\"\n    accent: \"柔和鼠尾草綠 (Sage Green) 或 乾枯玫瑰粉 (Dusty Rose)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 35\n  prohibited_elements: [\"硬性推銷文句\", \"過度飽和的圖表\", \"重複堆砌的條列句\"]\n  writing_style: \"優雅、克制、極具生活品味。用字遣詞需溫和知性，多用描繪生活型態或品牌哲學的詞彙，少用冰冷硬實的推銷字眼\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 哲學導入：以一句富含詩意與生活啟發的話作為前言，勾勒願景\"\n    - \"2. 經典剖析：用極簡的『一頁一核心』，展示產品/方案的最美細節\"\n    - \"3. 空間/生活型態：將方案融入日常，展示其在實際情境中的鬆弛美感\"\n    - \"4. 溫和致謝：以簡約留白和優雅文句收尾\""
    },
    {
        "id": "style-05",
        "tag": "文青質感",
        "name": "🧱 材質風格 (Texture Style)",
        "description": "強調厚重觸覺美感，融入清水模、磨砂玻璃與金屬壓鑄刻痕。",
        "applicable": "建築室內設計作品集、房產開發案介紹、高階硬體發表、高階財管服務",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：材質風格 (Texture Style)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Texture Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    grid: \"穩重、結構化的對稱格線系統，傳達嚴謹與安定感\"\n  styling:\n    tactile_textures: \"背景絕非單純平塗，必須帶有『清水模（Exposed Concrete）』、『細沙磨砂玻璃』或『拉絲金屬（Brushed Metal）』的微米級實體質感\"\n    depth_effect: \"文字與卡片物件需融入微弱的內陰影（Inner Shadows），營造出彷彿在石材、鋼板上『深雕拓印』或『金屬壓鑄』的立體凹陷層次\"\n    vibes: \"沉穩、不輕浮、具備匠人手作的實體物理分量，令人聯想到高級美術館建築或頂奢工藝品\"\n  color_palette:\n    background: \"清水模深灰 (Concrete Grey) 或 礦物暖灰 (Mineral Grey)\"\n    text: \"蝕刻古銅金 (Etched Bronze) 或 鋼琴烤漆黑\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"華而不實的修飾\", \"情緒化的驚嘆號\", \"跳躍的口俗俚語\"]\n  writing_style: \"專業、理性、權威。語氣需散發著無懈可擊的信任感與頂級工程學美感，用字精確洗鍊，直接用結構化陳述來說服觀眾\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 基石起源：介紹堅不可摧的核心基礎、初心與歷史脈絡\"\n    - \"2. 硬核工藝細節：一頁專注剖析一個關鍵材質、結構 or 技術指標\"\n    - \"3. 物理/商業實證：用穩健的大方塊展示經得起考驗的數據成果\"\n    - \"4. 永恆承諾：重申對品質、安全與長期耐用性的無上追求\""
    },
    {
        "id": "style-06",
        "tag": "文青質感",
        "name": "🖌️ 一筆畫水彩風格 (One-Line Art Watercolor)",
        "description": "極簡連續鋼筆線條與低飽和度莫蘭迪色系結合，展現成熟知性美。",
        "applicable": "保養香氛品牌、瑜伽身心靈課程、心理諮商教育、優雅知性女性向主題",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：一筆畫水彩風格 (One-Line Art Watercolor)\n# ==========================================\n\nstyle_config:\n  theme_name: \"One-Line Art Watercolor Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    lines: \"所有裝飾性圖示、人物輪廓或邊框，僅能使用單一連續、不中斷的細黑色鋼筆線（One-Line Art）勾勒\"\n  styling:\n    watercolor_wash: \"背景或卡片底色點綴低飽和度、半透明、邊緣帶有暈染水漬效果的水彩塊（Watercolor Wash）\"\n    vibes: \"無任何侵略性與生硬直角，極度溫柔、安靜、知性。散發成熟大人的生活美學與內在自我沉澱氛圍\"\n  color_palette:\n    background: \"微透粉的象牙白\"\n    watercolor: \"莫蘭迪粉 (Dusty Pink)、溫潤灰綠 (Sage)、薄霧藍 (Mist Blue)\"\n    strokes: \"極細木炭灰線\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"生硬冷僻的IT黑話\", \"侵略性的業務話術\", \"咆哮式的標題\"]\n  writing_style: \"溫暖、具備同理心與情感共鳴。文案要像一篇輕柔的手寫信，注重人性的溫度，循序漸進地引導與撫慰讀者\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 溫柔傾聽：點出我們內心深處被忽視的疲憊、痛點或渴望\"\n    - \"2. 療癒之光：引入能夠帶來舒緩、轉機或優雅提升的核心概念\"\n    - \"3. 漸進改變：用柔和的水彩塊承載步驟，輕柔地說明改善流程\"\n    - \"4. 平靜歸處：以優雅平靜的一句話，邀請觀眾共同踏上旅程\""
    },
    {
        "id": "style-07",
        "tag": "文青質感",
        "name": "🌸 日式和風風格 (Traditional Japanese)",
        "description": "傳統和紙金箔質感，打破對稱西洋格網，營造枯山水般的不對稱流動。",
        "applicable": "觀光旅遊、日式餐飲行銷、地方創生專案、跨國商務文化交流",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：日式和風風格 (Traditional Japanese)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Traditional Japanese Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    assymmetry: \"打破歐美教條式的絕對對稱與網格，採用『枯山水』般的不對稱美學，刻意保留空白角落\"\n    flow: \"排版引導線條應如和服衣褶、隨風飄散的櫻花，或流水般柔美不規則的『流動感』\"\n  styling:\n    textures: \"背景與物件卡片必須融入『手作和紙（Washi）』、偶爾穿插象徵尊貴的『金箔（Gold Leaf）』與『友禪染布料』細緻紋理\"\n    vibes: \"內斂、富有禪意、對細節懷有極致職人精神。大自然與人文歷史的和諧共生\"\n  color_palette:\n    background: \"極淡米和紙白\"\n    accents: \"緋紅 (Scarlet Red)、靛青 (Indigo Blue)、微亮箔金\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"王婆賣瓜的自我吹噓\", \"毫無意境的字眼\", \"雜亂無章的英文縮寫\"]\n  writing_style: \"謙遜、優雅、富有哲理深度。話不說滿，利用『留白美學（Ma）』讓讀者在字裡行間自行品味、感受產品或文化的厚度\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 緣起/致禮：謙和地帶出歷史由來、文化傳承或事物美好的緣起\"\n    - \"2. 職人造物：聚焦單一產品/方案，極致細膩地訴說背後的打磨工序\"\n    - \"3. 自然交融：展示本方案如何為使用者帶來和諧、平衡與心靈滿足\"\n    - \"4. 餘韻悠長：以一句充滿東方智慧或感謝之詞，留下不盡的餘韻\""
    },
    {
        "id": "style-08",
        "tag": "商務科技",
        "name": "👾 霓虹拼貼風格 (Neon Collage)",
        "description": "懷舊稿紙溫暖底色撞擊極現代螢光幾何圖形，呈現超現實未來科技感。",
        "applicable": "AI與區塊鏈技術白皮書發表、時尚趨勢預測、前衛學術演講(TED Talk)",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：霓虹拼貼風格 (Neon Collage)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Neon Collage Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    contrast: \"強烈的新舊材質、復古未來碰撞 (Retro-futuristic Clash)\"\n  styling:\n    clash_pattern: \"最底層背景使用溫暖、微泛黃的『懷舊米色九宮格稿紙』或『老報紙/牛皮紙底紋』，但上方物件與標記必須使用高亮度、刺眼的『螢光霓虹色幾何色塊與指示箭頭』\"\n    vibes: \"傳達『立足於深厚經典智慧，大膽進行顛覆性科技創新』的超現實賽博朋克美學\"\n  color_palette:\n    background: \"復古稿紙黃 (Warm Paper Beige)\"\n    neon: \"螢光黃 (Fluorescent Neon Yellow)、電子藍 (Cyber Blue)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"無趣的平庸文案\", \"保守中庸的商業套話\"]\n  writing_style: \"前衛、實驗性、極富科技洞察力。語氣冷峻而自信，敢於宣告新時代的到來，使用富有技術張力、思想領袖感的詞彙\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 智慧基石：引述經典傳統理論、手稿 or 歷史悠久的難題作為基石\"\n    - \"2. 科技變異：一頁介紹霓虹前沿技術如何粗暴而完美地打破上述瓶頸\"\n    - \"3. 數位拼貼藍圖：展示大數據、複雜演算法交融後生成的超現實新藍圖\"\n    - \"4. 未來啟航：號召敢於冒險的人共同進入下一個霓虹數位世代\""
    },
    {
        "id": "style-09",
        "tag": "商務科技",
        "name": "📱 裝置模型風格 (Device Mockup)",
        "description": "數位硬體視角置頂，純白或純黑背景，極限突出 App/SaaS 的 UI/UX 設計。",
        "applicable": "SaaS產品發表會、UI/UX設計師作品集、科技新創募資、數位行銷工具介紹",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：裝置模型風格 (Device Mockup)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Device Mockup Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    device_ratio: \"幻燈片核心必須有數位硬體（如：iPhone, iPad, MacBook, Apple Watch）的極致高精密度邊框模型，裝置畫面必須佔據版面 70% ~ 80%\"\n  styling:\n    backdrop: \"背景限定為極致乾淨的『無暇影棚白 (Studio White)』或『暗室無光黑 (Studio Black)』\"\n    focus: \"徹底消除一切不必要的裝飾、斑點或多餘線條。讓觀眾的視線完全聚焦於硬體螢幕中所呈現的 UI 界面細節與流暢操作\"\n    vibes: \"宛如 Apple 新品發表會的 Keynote 投影片，強調絕對的專注、科技工藝的無瑕與純粹\"\n  color_palette:\n    background: \"極致灰白 (Studio Grey-White)\"\n    accent: \"深沉科技黑\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"不著邊際的空泛修飾\", \"大段落文字\", \"花俏無意義的裝飾貼圖\"]\n  writing_style: \"產品與功能導向。極其乾淨利落，使用指引式的文案。多使用『點擊、一鍵流轉、無縫串接、即時呈現』等指向具體操作的詞語\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 舞台開口：裝置首頁震撼呈現，展示主介面美學與產品的核心價值主張\"\n    - \"2. 核心功能卡：將畫面聚焦在 iPhone/Mac 內部核心 UI，展示最亮眼的功能\"\n    - \"3. 無縫工作流：連續展示用戶從步驟 A ➜ 步驟 B 的絲滑無縫操作體驗\"\n    - \"4. 極致數據：在大螢幕裝置中顯示最終的轉換率、效率飆升指標\""
    },
    {
        "id": "style-10",
        "tag": "商務科技",
        "name": "🏙️ 3D 數位城市風格 (3D Digital Urban)",
        "description": "等角 45 度立體微縮模型，將抽象的物聯網與智慧系統轉化為精密數位孿生。",
        "applicable": "物聯網(IoT)解決方案、物流供應鏈管理、大型軟體系統架構、智慧城市開發",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：3D 數位城市風格 (3D Digital Urban)\n# ==========================================\n\nstyle_config:\n  theme_name: \"3D Digital Urban Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    perspective: \"強制採用 3D 等角投影視圖（Isometric 45-degree Perspective），使版面具備高度立體空間感\"\n    components: \"將抽象數據、伺服器節點、物流通道具象化為精緻、發光的『3D 微縮建築積木』、並使用立體連線（Neon Cables）相互連結\"\n  styling:\n    glow: \"暗色背景下，線條與節點自帶微弱的霓虹發光效果（Cyber Glow）\"\n    vibes: \"宛如經典遊戲《SimCity（模擬城市）》高科技版或頂級 3D CAD 建模系統，展現數位孿生（Digital Twin）的精準、複雜系統與掌控感\"\n  color_palette:\n    background: \"極深幽邃藍 (Midnight Blue)\"\n    glowing: \"螢光綠 (Fluorescent Green)、電光藍 (Electric Blue)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"雜亂的生活化口語\", \"過於感性的修飾\", \"大塊毫無結構的長句\"]\n  writing_style: \"宏觀、客觀、系統化。專注於闡述『節點、網絡、傳輸、反饋、同步、優化』。用字遣詞需充滿架構師、系統分析師的宏觀與精確\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 全域沙盤：展示城市/系統的 3D 全景等角視圖，定義宏觀框架與核心規模\"\n    - \"2. 骨幹網絡分解：剖析底層物理管線與數據中心『核心』，指出目前的瓶頸\"\n    - \"3. 智慧調度引擎：聚焦介紹智慧演算法/新系統接入後的運作變化\"\n    - \"4. 高效運轉實證：展示全面互聯、即時反饋後的系統高效率、低能耗數據\""
    },
    {
        "id": "style-11",
        "tag": "麥肯錫高階",
        "name": "🔺 高階顧問風 (The Minto Pyramid Principle)",
        "description": "金字塔原理結論先行，強制完整句子行動標題，呈現專業理性的戰略諮詢高數據密度排版。",
        "applicable": "2026年度營運策略、市場擴展方案、高階主管決策匯報、投資人回報",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：高階顧問風 (The Minto Pyramid Principle)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Minto Pyramid Strategy\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎯 2. 金字塔原理與行動標題約束 (Logic & Headers)\nlogic_constraints:\n  top_down_approach: \"每頁資訊架構必須遵循結論先行。先給出最核心決策結論，再條列支持該結論的關鍵子論據，遵循 MECE（相互獨立，完全窮盡）原則\"\n  action_titles: \"【強制要求】每張幻燈片的大標題『必須是一個完整、帶有動作或因果關係的句子』，直接陳述該頁的核心洞察或決策依據，嚴禁使用無意義的單純名詞。\"\n  examples:\n    correct: \"因供應鏈中斷，導致第二季市佔率下滑 5%，需啟動本土替代方案\"\n    incorrect: \"第二季市佔率分析與探討\"\n\n# 📊 3. 顧問式佈局與高數據密度 (Layout & Alignment)\nlayout_constraints:\n  layout_type: \"結構化對齊 (Structured Layout)，版面必須極致整潔，體現專業理性\"\n  grid: \"優先採用『左側文字核心邏輯，右側關鍵數據/圖表指標』或『三欄式戰略對策對比（方案一/方案二/方案三）』的並排結構\"\n  alignment: \"所有內文清單一律靠左對齊，絕不居中。每頁內容底部請務必預留空間，以 [資料來源：來源文件名稱] 的格式嚴格標示數據出處\"\n  tags:\n    key_insight: \"[關鍵洞察]\"\n    risk_indicator: \"[風險提示]\"\n\n# ✍️ 4. 文字精煉與專業語氣 (Text & Tone Constraints)\ntext_rules:\n  word_count_limit_per_slide: 60\n  prohibited_elements: [\"任何感性敘述\", \"故事性鋪陳\", \"非必要的裝飾性文句\"]\n  tone: \"語氣必須如同手術刀般冷靜精確、高度理性、決策導向。多使用『優化、提升、減緩、轉型、驅動、重組』等高階經理人商務語彙\""
    },
    {
        "id": "style-12",
        "tag": "麥肯錫高階",
        "name": "🧊 2.5D 立體風 (The Digital Sandbox)",
        "description": "積木模組化玩具精密感，極高留白與低密度文字，適合展現分層流向。",
        "applicable": "智慧城市物流網格架構、系統流程優化、複雜數據依賴關係展示",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：2.5D 立體風 (The Digital Sandbox)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Digital Sandbox Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🧱 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  modular_components: \"請將每個系統物件、節點或步驟，視為一個獨立的『積木零件』。每一頁幻燈片必須有清晰的幾何邊界感，資訊區塊要像方塊般整齊排列，拒絕雜亂無章的任意排版\"\n  layered_pipeline: \"本風格極度適合呈現流程與架構。在展示系統時，請依照『由上至下（Top-Down 層次）』或『由左至右（Pipeline 流向）』的邏輯推進，讓觀眾一眼能看出各部件之間的依賴與串聯關係\"\n  environmental_labels:\n    core_path: \"[核心]\"\n    success_path: \"[成功]\"\n    risk_point: \"[警示]\"\n\n# 🎯 3. 內容精簡與精確度規則 (Precision Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"長篇大論的複雜長句\", \"非結構化的段落\", \"故事化敘述\"]\n  layout_density: \"如同精緻的 3D 模型零件，文字必須極度精煉，留出大量空間以營造空間深度感。說明必須拆解成『短句』或『精準的步驟節點（例如：步驟 1 ➜ 步驟 2 ➜ 步驟 3）』\"\n  copywriting_style: \"文案語氣需具備工程、科技與結構感。標題應具備空間與元件質感（例如：使用『全域物流網格節點』而非傳統的『物流配送流程介紹』）\"\n\n# 📐 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 全域視角首頁 (Global Overview)：精煉的標題與一句話定義的系統架構核心\"\n    - \"2. 底層痛點 (Infrastructure Flaws)：條列式列出目前架構、流程或物流存在的瓶頸點 [警示]\"\n    - \"3. 分層解析 (Layer-by-Layer Modules)：每一頁只專注介紹一個核心層次（如：基礎硬體層 ➜ 數據傳輸層 ➜ 應用表現層）或一個流程節點\"\n    - \"4. 流暢運行效益 (Optimized Flow)：以具備對比性的精準短句，呈現優化後的流暢路徑 [成功]\""
    },
    {
        "id": "style-13",
        "tag": "麥肯錫高階",
        "name": "🗂️ 軟體服務風 (Soft UI / Card-Based)",
        "description": "極致留白的App介面質感，儀表板式雙欄佈局，操作導向的介面化文案。",
        "applicable": "企業內部簽核系統優化方案、CRM與管理後台升級展示、SaaS平台功能介紹",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：軟體服務風 (Soft UI / Card-Based)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Soft UI Card System\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  card_based_structure: \"請將每張幻燈片視為一個乾淨的 App 介面。資訊必須『模組化』拆解，一個區塊只講一件事情，各區塊之間要保持明顯的留白（Whitespace），視覺上絕不擁擠\"\n  dashboard_layout: \"在展示功能或流程時，優先採用『左側核心標題/短句，右側核心數據或條列組件』的左右雙欄結構，來模擬現代 SaaS 軟體後台的層次感\"\n  pill_labels: \"若遇到重要關鍵字、步驟狀態（如：高效、安全、全新上線、已完成），請一律使用 [標籤：文字] 的格式獨立標示\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 50\n  prohibited_elements: [\"長篇段落\", \"感性的故事鋪陳\", \"起承轉合的虛言\"]\n  text_density: \"每張幻燈片的總字數請嚴格控制在 40 到 50 字以內。過多的文字會破壞軟體介面的秩序感。所有說明必須拆解成精簡的『短句』或『條列式清單（Bullet Points）』\"\n  copywriting_style: \"標題與內文請使用現代軟體服務的精準、操作導向語氣。例如：使用『全方位數據監測』而非傳統的『系統監控功能介紹』\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 產品/方案首頁 (Dashboard Home)：精煉的標題與核心一句話價值主張\"\n    - \"2. 核心痛點 (System Issues)：條列式列出目前面臨的問題或系統痛點\"\n    - \"3. 功能與流程展示 (Features & Modules)：每一頁只專注介紹一個核心功能卡片或流程節點\"\n    - \"4. 預期效益 (Metrics Dashboard)：以具備對比性的短句呈現優化後的數據 or 效益\""
    },
    {
        "id": "style-1780791636163",
        "tag": "文青質感",
        "name": "➰科技水墨風格 (Tech-Ink Wash Elegance Style)",
        "description": "靈活非對稱佈局，融入大量「留白」美學，傳達虛實相生的動態意境。背景採『生宣紙』或『古絹絲』微米級紋理。文字邊界以『墨汁暈染』漸層過渡，營造虛實交織的立體層次。整體冷靜深邃，將前沿技術收斂於東方內斂美學。",
        "applicable": "深度技術分析、哲學思辨報告、高階概念演示、前沿趨勢預測。",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：科技水墨風格 (Tech-Ink Wash Elegance Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Tech-Ink Wash Elegance Style\"\nversion: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"靈活、非對稱的流動佈局，融入大量「留白」美學，傳達虛實相生的動態意境\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有手工『生宣紙（Raw Xuan Paper）』的微米級植物纖維紋理，或細緻半透明的『古絹絲』質感\"\ndepth_effect: \"文字與卡片物件邊界需融入『墨汁暈染（Ink Bleeding）』的漸層過渡效果，營造出彷彿墨跡在紙張纖維中自然擴散、虛實交織的立體層次\"\nvibes: \"冷靜、深邃、字字珠璣。將前沿技術的極致精準，收斂於古老東方的內斂美學中，令人聯想到當代水墨藝術展或高端多媒體數位藝廊\"\ncolor_palette:\nbackground: \"宣紙微黃 (Xuan White) 或 輕煙薄霧灰\"\ntext: \"松煙濃墨黑 (Pine Smoke Black) 或 枯筆淡墨灰\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 35\nprohibited_elements:\n- \"散文式的冗長贅字\"\n- \"情緒化的口語俚語\"\n- \"破壞留白感的密集資料堆砌\"\nwriting_style: \"冷靜、深邃、充滿哲學底蘊。行文節奏如大師揮毫，用字極其洗鍊，將硬核的深度學習術語與古典文學的行文韻律完美交織，直接以本質洞察說服聽眾\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 點睛破題（濃墨）：用一字千金的精煉陳述，如第一道濃墨直擊技術或議題的核心本質\"\n- \"2. 脈絡佈局（墨韻流動）：梳理底層架構或數據流，用具演進感的文字描述模組間的共振與解構\"\n- \"3. 虛實相生（細節與留白）：實處精準列出硬核指標與痛點，虛處以引用區塊延伸出引人深思的範式思考\"\n- \"4. 餘韻綿長（淡墨未來）：不給予封閉式的絕對結論，而是指出具前瞻性的延伸趨勢，留下寬廣的對話空間\"\n"
    },
    {
        "id": "style-1780793669053",
        "tag": "文青質感",
        "name": "📏手繪原稿插畫風格 (Hand-drawn Sketch & Illustration Style)",
        "description": "以粗糙的「重磅素描紙」為背景，採用自由奔放且不對稱的速寫佈局。文字與卡片邊緣呈現色鉛筆或麥克筆疊色的微透明層次，陰影由手繪斜線交織而成。整體充滿有機、不完美的創作者溫度，如同翻閱科學家的實驗筆記或動畫分鏡腳本，兼具知性與創造力。",
        "applicable": "概念發想、產品設計稿演示、技術架構拆解、科學實驗筆記、迭代藍圖說明",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：手繪原稿插畫風格 (Hand-drawn Sketch & Illustration Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Hand-drawn Sketch & Illustration Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"自由奔放的速寫佈局，排版帶有手稿的隨性與不對稱感，打破傳統網格的僵硬限制\"\nstyling:\ntactile_textures: \"背景呈現帶有粗糙顆粒感的『重磅素描紙（Heavyweight Sketchbook Paper）』或『輕質再生紙』，邊緣隱約可見鉛筆起草的淡灰色輔助線與毛邊\"\ndepth_effect: \"文字與卡片物件邊緣呈現『色鉛筆反覆疊色（Pencil Layering）』或『麥克筆疊塗』的微透明層次，卡片陰影則由密集的擬真手繪斜線（Hatching）交織而成\"\nvibes: \"充滿有機、不完美的創作者溫度，如同翻閱科學家的實驗筆記或動畫導演的動態分鏡腳本（Storyboard），兼具知性與創造力\"\ncolor_palette:\nbackground: \"象牙純質紙白 (Ivory Paper White) 或 復古牛皮紙褐\"\ntext: \"炭精筆深焦黑 (Charcoal Black) 或 普魯士藍手繪墨\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 42\nprohibited_elements: [\"生硬沉悶的法律條約式排版\", \"毫無修飾的數位預設字體感\", \"過度冷漠的官僚宣言\"]\nwriting_style: \"直白、具象、富有探險精神。如同設計師在白板上邊畫邊聊的互動感，善用生動的比喻與具體場景打破技術壁壘，語氣真誠且極具啟發性\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 靈感篝火（概念初繪）：從一個具體痛點的『第一道草圖』出發，勾勒出核心問題與探索起點\"\n- \"2. 結構解剖（線稿拆解）：如同工業設計透視圖般，將複雜的技術架構或數據流程拆解為清晰的手繪局部與邏輯線\"\n- \"3. 實證著色（色彩賦能）：用亮色調的手繪大方塊填入核心成果與關鍵指標，讓抽象的數據價值躍然紙上\"\n- \"4. 未完待續（藍圖延伸）：保留手稿邊緣未完成的延伸線條，象徵系統的持續演進，邀請聽眾加入未來的疊代旅程\"\n\n"
    },
    {
        "id": "style-1780795257476",
        "tag": "文青質感",
        "name": "🖇️中式書法狂草風格 (Chinese Wild Cursive Calligraphy Style)",
        "description": "狂放不羈的非對稱動態佈局。背景為生宣紙或絹帛的歲月紋理，局部穿插狂草飛白，搭配焦墨極致黑與硃砂落款紅。視覺強調枯筆焦墨層次，營造筆走龍蛇、氣勢磅礴的東方美學與立體力道。",
        "applicable": "戰略提案、趨勢分析、核心技術發布、高層匯報、重大變革宣言",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：中式書法狂草風格 (Chinese Wild Cursive Calligraphy Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Chinese Wild Cursive Calligraphy Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"大開大合、打破常規的縱向動態佈局，字裡行間如龍蛇飛舞，呈現氣勢磅礴的非對稱視覺節奏\"\nstyling:\ntactile_textures: \"背景帶有『手工生宣紙』或『粗織絹帛』的歲月紋理，局部穿插狂草獨有的『飛白（Flying White）』與潑墨乾枯對比的微米級實體質感\"\ndepth_effect: \"筆畫邊緣具備水分迅速被紙張吸乾的『枯筆焦墨層次』，重點物件伴隨『硃砂印章（Cinnabar Seal）』的微弱壓印下凹痕跡，營造墨跡入紙三分的立體力道\"\nvibes: \"狂放不羈、高能量、一氣呵成。將前沿技術的顛覆性力量，寄託於筆走龍蛇的東方線條美學中，令人聯想到當代前衛書法展或氣勢磅礴的交響樂章\"\ncolor_palette:\nbackground: \"歲月古紙黃 (Aged Parchment) 或 輕草灰\"\ntext: \"焦墨極致黑 (Charcoal Ink Black) 或 硃砂落款紅 (Cinnabar Red)\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 32\nprohibited_elements: [\"拘泥小節的逐條解釋\", \"毫無氣勢的平庸贅述\", \"死板對稱的框線約束\"]\nwriting_style: \"剛勁有力、氣勢如虹、字字珠璣。行文節奏大膽縱橫，將硬核科技核心提煉為具備情感張力與速度感的短句，直接以雷霆萬鈞的本質洞察震懾聽眾\"\n\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 揮毫落紙（亂象破局）：如狂草第一筆破空而來，以最辛辣、最深刻的痛點陳述，瞬間撕裂舊有格局\"\n- \"2. 筆走龍蛇（架構狂飆）：梳理核心技術的演進與爆發，用充滿流動感與速度感的線條隱喻，展現架構的縱橫交錯\"\n- \"3. 墨氣淋漓（硬核實證）：以飽滿、突出的硃砂紅色塊或巨型焦墨字體，甩出經得起時間考驗的震撼數據與核心成果\"\n- \"4. 意盡神遠（不羈未來）：收筆之處不設封閉框架，而是留下一道筆意未盡、具備強烈前瞻性的開放式思考，任由餘韻激盪\"\n\n"
    },
    {
        "id": "style-1780795591146",
        "tag": "文青質感",
        "name": "🆕 巴黎街頭時尚美學風格 (Parisian Street Fashion Aesthetics Style)",
        "description": "採用「Effortless Chic」排版，以高磅數未塗布紙或底片顆粒為背景。利用靈活留白、不對稱設計，搭配極簡細線框與高對比視覺落差，營造自信、慵懶且精準的高級訂製感，宛如頂級時尚雜誌內頁。",
        "applicable": "品牌策略提案、前沿技術介紹、高階設計審核、數據成果摘要",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：巴黎街頭時尚美學風格 (Parisian Street Fashion Aesthetics Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Parisian Street Fashion Aesthetics Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"經典、不費力的法式優雅（Effortless Chic）排版，刻意打破絕對對稱，利用靈活的留白與不對稱圖文呼應，傳達出鬆弛卻精準的高級訂製感\"\nstyling:\ntactile_textures: \"背景為帶有微細顆粒感的『高磅數未塗布紙（Uncoated Paper）』或『35mm底片復古顆粒質感』，物件邊緣乾淨俐落，彷彿頂級時尚雜誌的實體印刷內頁\"\ndepth_effect: \"文字與卡片邊界融入極致精細的『極簡細線框（Hairline Borders）』與輕微的『平面剪貼層次（Collage Depth）』，不使用重度漸層，而是靠高對比度的視覺落差營造低調的奢華感\"\nvibes: \"自信、極度精緻且毫不費力。將前沿技術的複雜硬核，收斂於慵懶且經典的時裝美學之中，令人聯想到巴黎時裝週外的精緻街拍或當代精品藝廊\"\ncolor_palette:\nbackground: \"經典風衣米白 (Trench Beige) 或 暮光冷石灰\"\ntext: \"高級訂製深邃黑 (Couture Black) 或 慵懶波爾多紅 (Bordeaux Red)\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 36\nprohibited_elements: [\"毫無個性的公式化贅詞\", \"廉價過時的口號標語\", \"破壞整體高冷感的密集表格\"]\nwriting_style: \"精準而克制、優雅而自信。行文如同時尚評論家般犀利，字字點到為止，拒絕平鋪直敘的冗長解釋，直接用最犀利的觀點與洗鍊的修辭震懾觀眾\"\n\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 街頭初見（經典序幕）：以最具反差感的核心痛點切入，如同走在香榭大道被一抹經典造型瞬間吸引，直擊問題本質\"\n- \"2. 高級剪裁（結構重塑）：如同高訂服裝的精準打版，將複雜的技術或商業模型進行完美拆解，只保留最具靈魂的骨架與線條\"\n- \"3. 天橋盛宴（硬核高潮）：用對比強烈、比例完美的精緻方塊，大膽展示無可挑剔的數據成果與最亮眼的關鍵核心指標\"\n- \"4. 經典不敗（風格延伸）：不給予平庸的封閉式結論，而是留下一個引人玩味、超越潮流的前瞻趨勢，讓優雅餘韻持續發酵\"\n\n"
    },
    {
        "id": "style-1780795758097",
        "tag": "活力數位",
        "name": "🆕 兒童粗蠟筆塗鴉風格 (Children's Thick Crayon Doodle Style)",
        "description": "背景是粗糙纖維感的圖畫紙，圖文採自由非線性排版，帶有童趣的輕微歪斜感。視覺由厚重、不均勻的粗蠟筆堆疊蠟質與筆屑痕跡構成，色塊呈現筆觸反覆塗抹的手工疊色效果，營造熱情奔放且富有直覺想像力的風格。",
        "applicable": "創意發想與提案、複雜概念簡化教學、初期研究成果發表、專案啟動簡報",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：兒童粗蠟筆塗鴉風格 (Children's Thick Crayon Doodle Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Children's Thick Crayon Doodle Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 擺放與視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry: grid: \"純真、不受拘束的自由非線性排版，圖文呈現自然錯落，帶有童趣的輕微歪斜與不對稱感\"\nstyling: tactile_textures: \"背景為帶有明顯粗糙纖維感的『八開白色圖畫紙（Drawing Paper）』，物件與文字邊緣具備厚重、不均勻的『粗蠟筆堆疊蠟質（Thick Crayon Wax）』與細微的筆屑痕跡\"\ndepth_effect: \"色塊與卡片呈現筆觸反覆塗抹、不完全飽和的『手工疊色效果』，陰影由粗蠟筆線條隨意橫劃的『排線重疊（Overlay Sketching）』組成，營造純物理的手作厚實度\"\nvibes: \"充滿童心、熱情奔放且富有直覺想像力。用不造作的純真視角簡化複雜世界，令人聯想到兒童繪畫展或充滿創意的塗鴉實驗室\"\ncolor_palette: background: \"溫暖圖畫紙白 (Sketchpad White) 或 太陽暖黃\" text: \"蠟筆濃炭黑 (Crayon Black) 或 飽和深海藍\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 38\nprohibited_elements: [\"晦澀難懂的學院派公式\", \"死板空洞的官僚文字\", \"毫無生氣的冷酷數據表格\"]\nwriting_style: \"直覺、純粹、富含聯想力。如同用孩子的眼睛看世界，將複雜的架構轉譯為最具象、好懂的『積木與玩具隱喻』，語氣真誠熱切，直接用最底層的本質打動聽眾\"\n\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n\"1. 好奇心的起點：從一個最根本、最直覺的提問出發，打破既定思維，大膽揭示核心痛點\"\n\"2. 積木大拆解：將複雜的技術模型或業務流程，拆解成最基礎、最容易理解的『基礎元件構造』\"\n\"3. 神奇玩具箱：用鮮豔、醒目的巨型蠟筆色塊，展示最具驚喜感與破壞力的數據成果與應用價值\"\n\"4. 下一站太空船：以充滿希望與想像力的筆觸勾勒出未來的演進方向，邀請聽眾攜手展開下一段冒險旅程\"\n\n"
    },
    {
        "id": "style-1780795954911",
        "tag": "商務科技",
        "name": "🆕 金融數據專家風格 (Financial Data Expert Style)",
        "description": "強調嚴謹的多維格線系統與資本市場效率。背景具高級財報壓紋或彭博終端像素網格，圖表邊緣帶有高頻電子看板微發光感。配色為深邃藍/石墨灰搭配增長翠綠/古銅金，風格極度理性沉穩。",
        "applicable": "量化投資策略報告、宏觀經濟分析、財報與壓力測試簡報、資產安全邊際報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：金融數據專家風格 (Financial Data Expert Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Financial Data Expert Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局约束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"矩陣式、極度嚴謹的多維數據格線系統，強調資本市場的秩序、流動性與極致效率\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有高級實體財報的『重磅防偽浮水印壓紋紙』質感，或彭博終端機（Bloomberg Terminal）特有的『微米級暗色電子像素網格』\"\ndepth_effect: \"數據圖表、K線指標與卡片物件邊界需融入『高頻電子看板』的微發光切面，或精細的『雷射防偽標籤』微幅凹凸層次，營造出資訊即時跳動與高價值資產的實體厚重感\"\nvibes: \"絕對理性、沉穩、具備掌控億級資本的決策分量。將瞬息萬變的市場波動收斂於無懈可擊的數學模型中，令人聯想到華爾街頂級對沖基金總部或瑞士私人銀行決策室\"\ncolor_palette:\nbackground: \"彭博終端深邃藍 (Terminal Navy) 或 華爾街冷石墨灰\"\ntext: \"資本增長翠綠 (Growth Green) 或 條金古銅金\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 42\nprohibited_elements: [\"空泛的市場營銷話術\", \"未經量化的主觀預測\", \"情緒化的驚嘆與誇大修飾\"]\nwriting_style: \"犀利、數據導向、具備極高信噪比。語氣沉穩且充滿市場權威感，用詞精確洗鍊，拒絕含糊的形容詞，直接以複利、夏普值（Sharpe Ratio）等硬核指標與量化因果進行邏輯說服\"\n\n\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n\"1. 市場宏觀定錨（Alpha 起源）：剖析當前宏觀經濟痛點、波動率或套利機會，以絕對客觀的市場事實定錨核心議題\"\n\"2. 量化模型架構（因子拆解）：如同資產定價模型，將複雜數據流拆解為底層的核心驅動因子、演算法與風險控管邏輯\"\n\"3. 壓力測試實證（資產負債表）：用剛性、高對比的數據方塊，甩出經得起歷史回測（Backtesting）與極限壓力測試的量化成果\"\n\"4. 風險邊際永續（終局策略）：重申資產安全邊際、最大回撤控制（Drawdown Control）與長期價值增長的前瞻演進藍圖\"\n\n"
    },
    {
        "id": "style-1780796523396",
        "tag": "文青質感",
        "name": "🆕 暖心繪本敘事風格 (Warning Heart Narrative Style)",
        "description": "自由有機的非對稱佈局，搭配手繪水彩紙紋理和色鉛筆觸感。視覺溫暖治癒，利用柔焦陰影和層疊，營造微縮模型般的立體繪本空間感，充滿詩意與魔幻寫實。",
        "applicable": "品牌故事、年度回顧、願景發布、企業文化傳達、公益活動報告、啟發性演講",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：暖心繪本敘事風格 (Warning Heart Narrative Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Warning Heart Narrative Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"自由、有機且富有故事感的非對稱佈局，文字與圖案留白交織，如同翻閱一本精緻的成人繪本\"\nstyling:\ntactile_textures: \"背景呈現細緻的『手繪水彩紙紋理（Watercolor Paper Grain）』，邊緣帶有淡淡的色鉛筆筆觸或輕微的毛邊感，拒絕死板的數位平塗\"\ndepth_effect: \"物件與文字微顯層疊，利用溫和的半透明光影與微弱的柔焦陰影，營造出彷彿『微縮模型（Mitate Miniature）』或立體繪本般的空間錯置感\"\nvibes: \"溫暖治癒、帶著一絲帶有詩意的孤獨與魔幻寫實。在宏大的日常場景中聚焦微小個體，激發情感共鳴與童心\"\ncolor_palette:\nbackground: \"夢幻暮光藍 (Twilight Blue) 或 溫暖繪本米黃\"\ntext: \"深夜手繪墨藍 (Midnight Ink) 或 森林深處綠\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 40\nprohibited_elements: [\"冰冷沉悶的商業教條\", \"過度堆砌的技術黑話\", \"毫無情感的純數據條列\"]\nwriting_style: \"富有詩意、獨白式的敘事語氣。將生硬的資訊轉化為帶有溫度、啟發性的故事線，用詞溫柔而深刻，點到為止，留給觀眾想像與感悟的空間\"\n\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n\"1. 遇見與迷惘：以都市或星空為隱喻，點出目前面臨的核心痛點或未知挑戰\"\n\"2. 微觀新視界：將視角縮小，像 1:87 的微縮世界般，專注剖析被忽略的關鍵技術細節或核心概念\"\n\"3. 溫暖的光點：將數據成果或解決方案轉化為旅程中遇見的驚喜，用具象、溫暖的大方塊承載核心價值\"\n\"4. 擁抱未知的旅程：重申願景，不給予生硬的終點，而是以開放且充滿希望的前瞻視角，邀觀眾一同前行\"\n\n"
    },
    {
        "id": "style-1780796719850",
        "tag": "麥肯錫高階",
        "name": "🆕 精密機械專家風格 (Precision Machinery Expert Style)",
        "description": "極致精準的工程幾何格線，背景為陽極氧化鋁或碳纖維質感。文字物件具CNC精密倒角與雷射雕刻線，營造組件嚴密互鎖的物理深度。風格冰冷、強悍、精確，配色為鈦金屬灰/深邃藍與冷光藍/安全橘。",
        "applicable": "技術規格報告、工程分析報告、品質控制報告、系統架構簡報、量化數據報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：精密機械專家風格 (Precision Machinery Expert Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Precision Machinery Expert Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"極致精準、微米級對稱的工程幾何格線系統，遵循嚴格的藍圖秩序，傳達零誤差的工業美學\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有航太級『陽極氧化鋁（Anodized Aluminum）』、微型『鈦合金蝕刻微線路』或輕量化『碳纖維編織（Carbon Fiber）』的微米級硬核實體質感\"\ndepth_effect: \"文字與卡片物件邊界展現出如同『CNC 數控銑削』的精密倒角（Chamfers）與階梯式凹槽，搭配極細的『雷射雕刻輔助線（Laser-etched Calibrations）』，營造出組件嚴密咬合與互鎖的多層次物理深度\"\nvibes: \"冰冷、強悍、極致精確且無懈可擊。將一切混亂轉化為可預測的齒輪嚙合與電路邏輯，令人聯想到半導體光刻機內部架構或瑞士頂級機械錶芯\"\ncolor_palette:\nbackground: \"航太鈦金屬灰 (Titanium Grey) 或 晶圓深邃藍\"\ntext: \"雷射冷光藍 (Laser Blue) 或 儀表板安全橘\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 60\nprohibited_elements: [\"模糊不清的概括形容\", \"感性非理性的情緒推論\", \"破壞系統精密度的雜亂無序排版\"]\nwriting_style: \"嚴謹、冷靜、高度結構化。字句如精密儀器產出的標定數據，用字精確至極，拒絕任何灰色地帶，直接以無懈可擊的邏輯推導與硬核因果關係說服觀眾\"\n\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 基準點校正（誤差溯源）：明確認定系統初始狀態與核心公差限制，直擊阻礙效率與穩定性的底層痛點\"\n- \"2. 動態傳動架構（核心解構）：將複雜系統拆解為高效嚙合的模組，剖析核心演算法與高精度控制流程\"\n- \"3. 額定效能實證（應力測試）：以剛性大方塊配合精密儀表數據，甩出經得起極限應力測試的量化指標與成果\"\n- \"4. 零故障願景（持續疊代）：定義長效穩定運作的封閉控制迴路（Closed-loop），提供具備高度可預測性的演進路徑\"\n\n"
    },
    {
        "id": "style-1780797576360",
        "tag": "活力數位",
        "name": "🆕 醜陋塗鴉風格 (Ugly Graffiti & Brutalist Doodle Style)",
        "description": "採用刻意不對稱的反設計佈局，背景使用街頭水泥牆或褶皺報紙等粗糙質感。物件以粗黑麥克筆重描邊和硬邊塊狀陰影，營造出叛逆、高能量且極具視覺衝擊",
        "applicable": "顛覆性創新提案、高衝突的市場痛點分析、反傳統策略報告、文化改革倡議",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：醜陋塗鴉風格 (Ugly Graffiti & Brutalist Doodle Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Ugly Graffiti & Brutalist Doodle Style\"\nversion: \"2026.1\"\n\n\n# 🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"刻意不對稱、歪斜且帶有衝突感的反設計（Anti-design）佈局，物件隨性重疊，打破一切常規格線\"\nstyling:\ntactile_textures: \"背景呈現帶有粗糙顆粒的『街頭水泥牆面』、被揉爛的『褶皺報紙』或『回收瓦楞紙板』質感，充滿未經加工的粗糙與原始感\"\ndepth_effect: \"文字與卡片物件使用『粗黑麥克筆重描邊（Hard Stroke）』，搭配完全沒有模糊半徑的『硬邊塊狀純黑陰影（Solid Drop Shadows）』，營造出強烈、甚至帶有刺眼感的手繪拼貼層次\"\nvibes: \"叛逆、高能量、未經修飾且極具視覺衝擊。如同地下樂團的 zine（獨立小報）或街頭塗鴉牆，用不完美的野性打破大企業的精緻偽裝\"\ncolor_palette:\nbackground: \"瓦楞紙屑褐 (Cardboard Brown) 或 街頭暴動水泥灰\"\ntext: \"噴漆極致死黑 (Graffiti Black) 或 螢光有毒綠 (Toxic Neon Green)\"\n\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 30\nprohibited_elements: [\"虛偽溫和的客套修飾\", \"平庸無奇的官僚匯報\", \"對稱工整的排版美學\"]\nwriting_style: \"銳利、直白、帶有挑釁與諷刺感的幽默語氣。直接撕開企業黑話的糖衣，用最粗暴但一針見血的動詞直擊底層邏輯，話語充滿野蠻生長的生命力\"# 📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 砸碎現狀（痛點引爆）：用最挑釁的提問或震撼事實，一棒敲碎市場的集體盲點與假象\"\n- \"2. 混亂核心（底層真相）：撕開漂亮的架構圖，直接展示最真實、未經美化的核心技術缺陷或市場本質\"\n- \"3. 野蠻生長（瘋狂實證）：用粗暴、醒目的巨型螢光色方塊，甩出經得起拷問的硬核數據與顛覆性成果\"\n- \"4. 朋克不死（持續顛覆）：拒絕給出安穩的傳統結論，而是拋出一個具備煽動性的前瞻議題，挑動聽眾的既有認知\"\n\n"
    }
];