window.notebookStylesData = [
    {
        "id": "style-01",
        "tag": "活力數位",
        "name": "💥 數位普普風格 (Digital Pop)",
        "description": "採用有機形狀與高彩度配色，消除科技冰冷感，極具社群親和力。",
        "applicable": "年輕族群行銷提案、創意發想會議、新創募資簡報、教育培訓",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：數位普普風格 (Digital Pop)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Digital Pop Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    organic_shapes: true\n    avoid_perfect_shapes: \"嚴禁使用完美的正方形、長方形或正圓形色塊\"\n    key_elements: [\"變形蟲（Amoeba）\", \"不規則雲朵\", \"帶有微小手繪抖動感（Hand-drawn Jittery）的粗線條\"]\n  styling:\n    border_rules: \"所有文字框、圖片容器與卡片邊緣，必須加上 2px - 3px 的粗黑色實線邊框\"\n    shadow_effect: \"啟用重影黑影（Hard Drop Shadows），使視覺元件呈現如同復古貼紙堆疊的物理感\"\n    vibes: \"模擬 Instagram 限時動態、手寫便利貼（Post-it）與拼貼塗鴉，營造親切、不妥協、活力充沛的氛圍\"\n  color_palette:\n    primary: \"高彩度糖果色 (High-Chroma Candy Colors)\"\n    accent: \"螢光黃 (Fluorescent Yellow)、酸橙綠 (Lime Green)\"\n    neutral: \"米白底色搭配碳黑框線，拒絕死板純白\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"長篇大論\", \"學術官腔\", \"冰冷硬直的數據羅列\"]\n  writing_style: \"口語化、具高度煽動力與情緒渲染力的對話感。句首與關鍵處必須適度穿插 Emoji（例如：💥, 🎨, 🚀, 👀）\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 痛點大吐槽：用幽默好笑的例子切入目前市面上的不合理現狀\"\n    - \"2. 創意點子大爆發：一頁展示一個顛覆傳統的瘋狂好點子\"\n    - \"3. 成果與未來願景：用高彩度圖形模組展示我們對未來的想像\"\n    - \"4. 行動呼籲：給觀眾一個極具社群感的 Call to Action（CTA）\""
    },
    {
        "id": "style-02",
        "tag": "活力數位",
        "name": "⚡ 運動能量風格 (Sports Energy)",
        "description": "利用傾斜幾何與強烈高能對比色，創造極致的速度感與視覺張力。",
        "applicable": "業務團隊目標大會、競爭對手分析、健身/遊戲/科技新品提案",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：運動能量風格 (Sports Energy)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Sports Energy Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    dynamic_shapes: true\n    tilted_angle: \"所有色塊、圖片容器與裝飾元素必須強制右傾斜 15 度，或使用平行四邊形（Parallelogram）\"\n    split_lines: \"使用粗獷、銳利的斜向分割線（Slashed Cuts）來區分各個資訊欄位\"\n  styling:\n    motion_blur: \"背景與點綴條紋需呈現動態條紋感，引導觀眾視線向前延伸\"\n    vibes: \"運動跑道、賽車場上的瞬息萬變，強烈激發團隊成員的戰鬥力與危機意識\"\n  color_palette:\n    primary: \"極速黃 (Speed Yellow)、火焰橙 (Blaze Orange)\"\n    background: \"碳黑 (Carbon Black) 或 深邃灰 (Deep Charcoal)，營造暗色系的高級競技感\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"被動句式\", \"冗長鋪陳\", \"委婉推託之詞\"]\n  writing_style: \"高能量、爆發式文案。大量使用高強度、指向明確的主動動詞（例如：擊碎、突破、超越、碾壓、狂飆）。避免多餘的助詞\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 危機/目標宣告：指出不得不突破的燃眉之急與絕對死線\"\n    - \"2. 戰術解鎖：一頁一戰術，以強烈的傾斜卡片展示核心突圍手段\"\n    - \"3. 競爭力對決：使用高對比雙欄，一針見血對抗主要競爭對手\"\n    - \"4. 全力衝刺：終極目標數據的具象化，號召團隊全員全速前進\""
    },
    {
        "id": "style-03",
        "tag": "活力數位",
        "name": "🏛️ 古典普普風格 (Classical Pop)",
        "description": "將希臘羅馬古典藝術與現代消費符號強制碰撞，形成高記憶點的違和趣味。",
        "applicable": "廣告創意提案、Z 世代趨勢報告、新舊融合主題、尾牙/競賽開場",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：古典普普風格 (Classical Pop)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Classical Pop Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    collage_style: \"極限違和感拼貼 (Anachronistic Collage)\"\n    visual_clash: \"將莊嚴優雅的希臘羅馬大理石雕像、文藝復興名畫，強行搭配現代叛逆消費符號（如：墨鏡、泡泡糖、玩自拍、喝汽水）\"\n  styling:\n    background_patterns: \"使用半調網點（Halftone Dots）或孟菲斯（Memphis）幾何圖案作為點綴底紋\"\n    vibes: \"藝術感與荒謬惡搞並存，利用高級藝術與街頭文化的強烈反差，營造過目難忘的視覺幽默與前衛美感\"\n  color_palette:\n    primary: \"古典大理石灰 (Statue Grey)\"\n    accent: \"螢光桃紅 (Shocking Pink)、酸性藍 (Acid Blue)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"死板的純技術說明\", \"照本宣科的簡報\"]\n  writing_style: \"『一本正經地講幹話』。標題必須顯得極為莊嚴宏大、富含歷史感；但內文與數據說明卻要直白、辛辣、富含 Z 世代的自嘲與幽默\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 古老包袱：列出傳統思維中沉重、令人昏昏欲睡的古板現狀\"\n    - \"2. 荒謬吐槽：揭露當前痛點在現代人眼中有多麼荒謬可笑\"\n    - \"3. 顛覆性創新解法：將新技術/新創意包裝為『新古典啟蒙』展示\"\n    - \"4. 破圈宣言：呼籲大膽打破框架，跨界狂歡\""
    },
    {
        "id": "style-04",
        "tag": "文青質感",
        "name": "📖 現代雜誌風格 (Modern Magazine)",
        "description": "模擬高級生活雜誌排版，捨棄一切多餘邊框，以高雅留白與精美比例取勝。",
        "applicable": "品牌形象手冊、香氛家居行銷企劃、人資文化手冊、藝術展覽導覽",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：現代雜誌風格 (Modern Magazine)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Modern Magazine Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    layout_type: \"極簡無邊框 (Editorial Sans-Border)\"\n    whitespace_ratio: \"幻燈片四周保留至少 15%-20% 的『呼吸留白』，嚴禁使用任何實線邊框或明顯的表格隔線\"\n  styling:\n    typography_contrast: \"完全依靠超大字體（模擬雜誌頭條）與極小註解文字的強烈比例對比，來引導閱讀視線\"\n    vibes: \"散發類似《Vogue》、《Kinfolk》或《Cereal》的高端實體印刷品氛圍，強調高級感、慢步調、從容不迫\"\n  color_palette:\n    background: \"暖乳白色 (Warm Milk)、純淨燕麥色 (Oatmeal)\"\n    primary: \"深炭灰 (Charcoal Black)\"\n    accent: \"柔和鼠尾草綠 (Sage Green) 或 乾枯玫瑰粉 (Dusty Rose)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 35\n  prohibited_elements: [\"硬性推銷文句\", \"過度飽和的圖表\", \"重複堆砌的條列句\"]\n  writing_style: \"優雅、克制、極具生活品味。用字遣詞需溫和知性，多用描繪生活型態或品牌哲學的詞彙，少用冰冷硬實的推銷字眼\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 哲學導入：以一句富含詩意與生活啟發的話作為前言，勾勒願景\"\n    - \"2. 經典剖析：用極簡的『一頁一核心』，展示產品/方案的最美細節\"\n    - \"3. 空間/生活型態：將方案融入日常，展示其在實際情境中的鬆弛美感\"\n    - \"4. 溫和致謝：以簡約留白和優雅文句收尾\""
    },
    {
        "id": "style-05",
        "tag": "文青質感",
        "name": "🧱 材質風格 (Texture Style)",
        "description": "強調厚重觸覺美感，融入清水模、磨砂玻璃與金屬壓鑄刻痕。",
        "applicable": "建築室內設計作品集、房產開發案介紹、高階硬體發表、高階財管服務",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：材質風格 (Texture Style)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Texture Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    grid: \"穩重、結構化的對稱格線系統，傳達嚴謹與安定感\"\n  styling:\n    tactile_textures: \"背景絕非單純平塗，必須帶有『清水模（Exposed Concrete）』、『細沙磨砂玻璃』或『拉絲金屬（Brushed Metal）』的微米級實體質感\"\n    depth_effect: \"文字與卡片物件需融入微弱的內陰影（Inner Shadows），營造出彷彿在石材、鋼板上『深雕拓印』或『金屬壓鑄』的立體凹陷層次\"\n    vibes: \"沉穩、不輕浮、具備匠人手作的實體物理分量，令人聯想到高級美術館建築或頂奢工藝品\"\n  color_palette:\n    background: \"清水模深灰 (Concrete Grey) 或 礦物暖灰 (Mineral Grey)\"\n    text: \"蝕刻古銅金 (Etched Bronze) 或 鋼琴烤漆黑\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"華而不實的修飾\", \"情緒化的驚嘆號\", \"跳躍的口俗俚語\"]\n  writing_style: \"專業、理性、權威。語氣需散發著無懈可擊的信任感與頂級工程學美感，用字精確洗鍊，直接用結構化陳述來說服觀眾\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 基石起源：介紹堅不可摧的核心基礎、初心與歷史脈絡\"\n    - \"2. 硬核工藝細節：一頁專注剖析一個關鍵材質、結構 or 技術指標\"\n    - \"3. 物理/商業實證：用穩健的大方塊展示經得起考驗的數據成果\"\n    - \"4. 永恆承諾：重申對品質、安全與長期耐用性的無上追求\""
    },
    {
        "id": "style-06",
        "tag": "文青質感",
        "name": "🖌️ 一筆畫水彩風格 (One-Line Art Watercolor)",
        "description": "極簡連續鋼筆線條與低飽和度莫蘭迪色系結合，展現成熟知性美。",
        "applicable": "保養香氛品牌、瑜伽身心靈課程、心理諮商教育、優雅知性女性向主題",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：一筆畫水彩風格 (One-Line Art Watercolor)\n# ==========================================\n\nstyle_config:\n  theme_name: \"One-Line Art Watercolor Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    lines: \"所有裝飾性圖示、人物輪廓或邊框，僅能使用單一連續、不中斷的細黑色鋼筆線（One-Line Art）勾勒\"\n  styling:\n    watercolor_wash: \"背景或卡片底色點綴低飽和度、半透明、邊緣帶有暈染水漬效果的水彩塊（Watercolor Wash）\"\n    vibes: \"無任何侵略性與生硬直角，極度溫柔、安靜、知性。散發成熟大人的生活美學與內在自我沉澱氛圍\"\n  color_palette:\n    background: \"微透粉的象牙白\"\n    watercolor: \"莫蘭迪粉 (Dusty Pink)、溫潤灰綠 (Sage)、薄霧藍 (Mist Blue)\"\n    strokes: \"極細木炭灰線\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"生硬冷僻的IT黑話\", \"侵略性的業務話術\", \"咆哮式的標題\"]\n  writing_style: \"溫暖、具備同理心與情感共鳴。文案要像一篇輕柔的手寫信，注重人性的溫度，循序漸進地引導與撫慰讀者\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 溫柔傾聽：點出我們內心深處被忽視的疲憊、痛點或渴望\"\n    - \"2. 療癒之光：引入能夠帶來舒緩、轉機或優雅提升的核心概念\"\n    - \"3. 漸進改變：用柔和的水彩塊承載步驟，輕柔地說明改善流程\"\n    - \"4. 平靜歸處：以優雅平靜的一句話，邀請觀眾共同踏上旅程\""
    },
    {
        "id": "style-07",
        "tag": "文青質感",
        "name": "🌸 日式和風風格 (Traditional Japanese)",
        "description": "傳統和紙金箔質感，打破對稱西洋格網，營造枯山水般的不對稱流動。",
        "applicable": "觀光旅遊、日式餐飲行銷、地方創生專案、跨國商務文化交流",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：日式和風風格 (Traditional Japanese)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Traditional Japanese Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    assymmetry: \"打破歐美教條式的絕對對稱與網格，採用『枯山水』般的不對稱美學，刻意保留空白角落\"\n    flow: \"排版引導線條應如和服衣褶、隨風飄散的櫻花，或流水般柔美不規則的『流動感』\"\n  styling:\n    textures: \"背景與物件卡片必須融入『手作和紙（Washi）』、偶爾穿插象徵尊貴的『金箔（Gold Leaf）』與『友禪染布料』細緻紋理\"\n    vibes: \"內斂、富有禪意、對細節懷有極致職人精神。大自然與人文歷史的和諧共生\"\n  color_palette:\n    background: \"極淡米和紙白\"\n    accents: \"緋紅 (Scarlet Red)、靛青 (Indigo Blue)、微亮箔金\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"王婆賣瓜的自我吹噓\", \"毫無意境的字眼\", \"雜亂無章的英文縮寫\"]\n  writing_style: \"謙遜、優雅、富有哲理深度。話不說滿，利用『留白美學（Ma）』讓讀者在字裡行間自行品味、感受產品或文化的厚度\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 緣起/致禮：謙和地帶出歷史由來、文化傳承或事物美好的緣起\"\n    - \"2. 職人造物：聚焦單一產品/方案，極致細膩地訴說背後的打磨工序\"\n    - \"3. 自然交融：展示本方案如何為使用者帶來和諧、平衡與心靈滿足\"\n    - \"4. 餘韻悠長：以一句充滿東方智慧或感謝之詞，留下不盡的餘韻\""
    },
    {
        "id": "style-08",
        "tag": "商務科技",
        "name": "👾 霓虹拼貼風格 (Neon Collage)",
        "description": "懷舊稿紙溫暖底色撞擊極現代螢光幾何圖形，呈現超現實未來科技感。",
        "applicable": "AI與區塊鏈技術白皮書發表、時尚趨勢預測、前衛學術演講(TED Talk)",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：霓虹拼貼風格 (Neon Collage)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Neon Collage Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    contrast: \"強烈的新舊材質、復古未來碰撞 (Retro-futuristic Clash)\"\n  styling:\n    clash_pattern: \"最底層背景使用溫暖、微泛黃的『懷舊米色九宮格稿紙』或『老報紙/牛皮紙底紋』，但上方物件與標記必須使用高亮度、刺眼的『螢光霓虹色幾何色塊與指示箭頭』\"\n    vibes: \"傳達『立足於深厚經典智慧，大膽進行顛覆性科技創新』的超現實賽博朋克美學\"\n  color_palette:\n    background: \"復古稿紙黃 (Warm Paper Beige)\"\n    neon: \"螢光黃 (Fluorescent Neon Yellow)、電子藍 (Cyber Blue)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"無趣的平庸文案\", \"保守中庸的商業套話\"]\n  writing_style: \"前衛、實驗性、極富科技洞察力。語氣冷峻而自信，敢於宣告新時代的到來，使用富有技術張力、思想領袖感的詞彙\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 智慧基石：引述經典傳統理論、手稿 or 歷史悠久的難題作為基石\"\n    - \"2. 科技變異：一頁介紹霓虹前沿技術如何粗暴而完美地打破上述瓶頸\"\n    - \"3. 數位拼貼藍圖：展示大數據、複雜演算法交融後生成的超現實新藍圖\"\n    - \"4. 未來啟航：號召敢於冒險的人共同進入下一個霓虹數位世代\""
    },
    {
        "id": "style-09",
        "tag": "商務科技",
        "name": "📱 裝置模型風格 (Device Mockup)",
        "description": "數位硬體視角置頂，純白或純黑背景，極限突出 App/SaaS 的 UI/UX 設計。",
        "applicable": "SaaS產品發表會、UI/UX設計師作品集、科技新創募資、數位行銷工具介紹",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：裝置模型風格 (Device Mockup)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Device Mockup Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    device_ratio: \"幻燈片核心必須有數位硬體（如：iPhone, iPad, MacBook, Apple Watch）的極致高精密度邊框模型，裝置畫面必須佔據版面 70% ~ 80%\"\n  styling:\n    backdrop: \"背景限定為極致乾淨的『無暇影棚白 (Studio White)』或『暗室無光黑 (Studio Black)』\"\n    focus: \"徹底消除一切不必要的裝飾、斑點或多餘線條。讓觀眾的視線完全聚焦於硬體螢幕中所呈現的 UI 界面細節與流暢操作\"\n    vibes: \"宛如 Apple 新品發表會的 Keynote 投影片，強調絕對的專注、科技工藝的無瑕與純粹\"\n  color_palette:\n    background: \"極致灰白 (Studio Grey-White)\"\n    accent: \"深沉科技黑\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"不著邊際的空泛修飾\", \"大段落文字\", \"花俏無意義的裝飾貼圖\"]\n  writing_style: \"產品與功能導向。極其乾淨利落，使用指引式的文案。多使用『點擊、一鍵流轉、無縫串接、即時呈現』等指向具體操作的詞語\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 舞台開口：裝置首頁震撼呈現，展示主介面美學與產品的核心價值主張\"\n    - \"2. 核心功能卡：將畫面聚焦在 iPhone/Mac 內部核心 UI，展示最亮眼的功能\"\n    - \"3. 無縫工作流：連續展示用戶從步驟 A ➜ 步驟 B 的絲滑無縫操作體驗\"\n    - \"4. 極致數據：在大螢幕裝置中顯示最終的轉換率、效率飆升指標\""
    },
    {
        "id": "style-10",
        "tag": "商務科技",
        "name": "🏙️ 3D 數位城市風格 (3D Digital Urban)",
        "description": "等角 45 度立體微縮模型，將抽象的物聯網與智慧系統轉化為精密數位孿生。",
        "applicable": "物聯網(IoT)解決方案、物流供應鏈管理、大型軟體系統架構、智慧城市開發",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：3D 數位城市風格 (3D Digital Urban)\n# ==========================================\n\nstyle_config:\n  theme_name: \"3D Digital Urban Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  geometry:\n    perspective: \"強制採用 3D 等角投影視圖（Isometric 45-degree Perspective），使版面具備高度立體空間感\"\n    components: \"將抽象數據、伺服器節點、物流通道具象化為精緻、發光的『3D 微縮建築積木』、並使用立體連線（Neon Cables）相互連結\"\n  styling:\n    glow: \"暗色背景下，線條與節點自帶微弱的霓虹發光效果（Cyber Glow）\"\n    vibes: \"宛如經典遊戲《SimCity（模擬城市）》高科技版或頂級 3D CAD 建模系統，展現數位孿生（Digital Twin）的精準、複雜系統與掌控感\"\n  color_palette:\n    background: \"極深幽邃藍 (Midnight Blue)\"\n    glowing: \"螢光綠 (Fluorescent Green)、電光藍 (Electric Blue)\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 45\n  prohibited_elements: [\"雜亂的生活化口語\", \"過於感性的修飾\", \"大塊毫無結構的長句\"]\n  writing_style: \"宏觀、客觀、系統化。專注於闡述『節點、網絡、傳輸、反饋、同步、優化』。用字遣詞需充滿架構師、系統分析師的宏觀與精確\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 全域沙盤：展示城市/系統的 3D 全景等角視圖，定義宏觀框架與核心規模\"\n    - \"2. 骨幹網絡分解：剖析底層物理管線與數據中心『核心』，指出目前的瓶頸\"\n    - \"3. 智慧調度引擎：聚焦介紹智慧演算法/新系統接入後的運作變化\"\n    - \"4. 高效運轉實證：展示全面互聯、即時反饋後的系統高效率、低能耗數據\""
    },
    {
        "id": "style-11",
        "tag": "麥肯錫高階",
        "name": "🔺 高階顧問風 (The Minto Pyramid Principle)",
        "description": "金字塔原理結論先行，強制完整句子行動標題，呈現專業理性的戰略諮詢高數據密度排版。",
        "applicable": "2026年度營運策略、市場擴展方案、高階主管決策匯報、投資人回報",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：高階顧問風 (The Minto Pyramid Principle)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Minto Pyramid Strategy\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎯 2. 金字塔原理與行動標題約束 (Logic & Headers)\nlogic_constraints:\n  top_down_approach: \"每頁資訊架構必須遵循結論先行。先給出最核心決策結論，再條列支持該結論的關鍵子論據，遵循 MECE（相互獨立，完全窮盡）原則\"\n  action_titles: \"【強制要求】每張幻燈片的大標題『必須是一個完整、帶有動作或因果關係的句子』，直接陳述該頁的核心洞察或決策依據，嚴禁使用無意義的單純名詞。\"\n  examples:\n    correct: \"因供應鏈中斷，導致第二季市佔率下滑 5%，需啟動本土替代方案\"\n    incorrect: \"第二季市佔率分析與探討\"\n\n# 📊 3. 顧問式佈局與高數據密度 (Layout & Alignment)\nlayout_constraints:\n  layout_type: \"結構化對齊 (Structured Layout)，版面必須極致整潔，體現專業理性\"\n  grid: \"優先採用『左側文字核心邏輯，右側關鍵數據/圖表指標』或『三欄式戰略對策對比（方案一/方案二/方案三）』的並排結構\"\n  alignment: \"所有內文清單一律靠左對齊，絕不居中。每頁內容底部請務必預留空間，以 [資料來源：來源文件名稱] 的格式嚴格標示數據出處\"\n  tags:\n    key_insight: \"[關鍵洞察]\"\n    risk_indicator: \"[風險提示]\"\n\n# ✍️ 4. 文字精煉與專業語氣 (Text & Tone Constraints)\ntext_rules:\n  word_count_limit_per_slide: 60\n  prohibited_elements: [\"任何感性敘述\", \"故事性鋪陳\", \"非必要的裝飾性文句\"]\n  tone: \"語氣必須如同手術刀般冷靜精確、高度理性、決策導向。多使用『優化、提升、減緩、轉型、驅動、重組』等高階經理人商務語彙\""
    },
    {
        "id": "style-12",
        "tag": "麥肯錫高階",
        "name": "🧊 2.5D 立體風 (The Digital Sandbox)",
        "description": "積木模組化玩具精密感，極高留白與低密度文字，適合展現分層流向。",
        "applicable": "智慧城市物流網格架構、系統流程優化、複雜數據依賴關係展示",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：2.5D 立體風 (The Digital Sandbox)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Digital Sandbox Style\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🧱 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  modular_components: \"請將每個系統物件、節點或步驟，視為一個獨立的『積木零件』。每一頁幻燈片必須有清晰的幾何邊界感，資訊區塊要像方塊般整齊排列，拒絕雜亂無章的任意排版\"\n  layered_pipeline: \"本風格極度適合呈現流程與架構。在展示系統時，請依照『由上至下（Top-Down 層次）』或『由左至右（Pipeline 流向）』的邏輯推進，讓觀眾一眼能看出各部件之間的依賴與串聯關係\"\n  environmental_labels:\n    core_path: \"[核心]\"\n    success_path: \"[成功]\"\n    risk_point: \"[警示]\"\n\n# 🎯 3. 內容精簡與精確度規則 (Precision Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 40\n  prohibited_elements: [\"長篇大論的複雜長句\", \"非結構化的段落\", \"故事化敘述\"]\n  layout_density: \"如同精緻的 3D 模型零件，文字必須極度精煉，留出大量空間以營造空間深度感。說明必須拆解成『短句』或『精準的步驟節點（例如：步驟 1 ➜ 步驟 2 ➜ 步驟 3）』\"\n  copywriting_style: \"文案語氣需具備工程、科技與結構感。標題應具備空間與元件質感（例如：使用『全域物流網格節點』而非傳統的『物流配送流程介紹』）\"\n\n# 📐 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 全域視角首頁 (Global Overview)：精煉的標題與一句話定義的系統架構核心\"\n    - \"2. 底層痛點 (Infrastructure Flaws)：條列式列出目前架構、流程或物流存在的瓶頸點 [警示]\"\n    - \"3. 分層解析 (Layer-by-Layer Modules)：每一頁只專注介紹一個核心層次（如：基礎硬體層 ➜ 數據傳輸層 ➜ 應用表現層）或一個流程節點\"\n    - \"4. 流暢運行效益 (Optimized Flow)：以具備對比性的精準短句，呈現優化後的流暢路徑 [成功]\""
    },
    {
        "id": "style-13",
        "tag": "麥肯錫高階",
        "name": "🗂️ 軟體服務風 (Soft UI / Card-Based)",
        "description": "極致留白的App介面質感，儀表板式雙欄佈局，操作導向的介面化文案。",
        "applicable": "企業內部簽核系統優化方案、CRM與管理後台升級展示、SaaS平台功能介紹",
        "instructions": "# ==========================================\n# NotebookLM 簡報風格配置文件：軟體服務風 (Soft UI / Card-Based)\n# ==========================================\n\nstyle_config:\n  theme_name: \"Soft UI Card System\"\n  version: \"2026.1\"\n\n# 🛠️ 1. 簡報基本資訊\npresentation_info:\n  title: \"{{THEME_TITLE}}\"\n  target_pages: \"{{TARGET_PAGES}}\"\n  language: \"zh-TW\"\n\n# 🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\n  card_based_structure: \"請將每張幻燈片視為一個乾淨的 App 介面。資訊必須『模組化』拆解，一個區塊只講一件事情，各區塊之間要保持明顯的留白（Whitespace），視覺上絕不擁擠\"\n  dashboard_layout: \"在展示功能或流程時，優先採用『左側核心標題/短句，右側核心數據或條列組件』的左右雙欄結構，來模擬現代 SaaS 軟體後台的層次感\"\n  pill_labels: \"若遇到重要關鍵字、步驟狀態（如：高效、安全、全新上線、已完成），請一律使用 [標籤：文字] 的格式獨立標示\"\n\n# ✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\n  word_count_limit_per_slide: 50\n  prohibited_elements: [\"長篇段落\", \"感性的故事鋪陳\", \"起承轉合的虛言\"]\n  text_density: \"每張幻燈片的總字數請嚴格控制在 40 到 50 字以內。過多的文字會破壞軟體介面的秩序感。所有說明必須拆解成精簡的『短句』或『條列式清單（Bullet Points）』\"\n  copywriting_style: \"標題與內文請使用現代軟體服務的精準、操作導向語氣。例如：使用『全方位數據監測』而非傳統的『系統監控功能介紹』\"\n\n# 📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\n  sequence:\n    - \"1. 產品/方案首頁 (Dashboard Home)：精煉的標題與核心一句話價值主張\"\n    - \"2. 核心痛點 (System Issues)：條列式列出目前面臨的問題或系統痛點\"\n    - \"3. 功能與流程展示 (Features & Modules)：每一頁只專注介紹一個核心功能卡片或流程節點\"\n    - \"4. 預期效益 (Metrics Dashboard)：以具備對比性的短句呈現優化後的數據 or 效益\""
    },
    {
        "id": "style-1780791636163",
        "tag": "文青質感",
        "name": "➰科技水墨風格 (Tech-Ink Wash Elegance Style)",
        "description": "靈活非對稱佈局，融入大量「留白」美學，傳達虛實相生的動態意境。背景採『生宣紙』或『古絹絲』微米級紋理。文字邊界以『墨汁暈染』漸層過渡，營造虛實交織的立體層次。整體冷靜深邃，將前沿技術收斂於東方內斂美學。",
        "applicable": "深度技術分析、哲學思辨報告、高階概念演示、前沿趨勢預測。",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：科技水墨風格 (Tech-Ink Wash Elegance Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Tech-Ink Wash Elegance Style\"\nversion: \"2026.1\"\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"靈活、非對稱的流動佈局，融入大量「留白」美學，傳達虛實相生的動態意境\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有手工『生宣紙（Raw Xuan Paper）』的微米級植物纖維紋理，或細緻半透明的『古絹絲』質感\"\ndepth_effect: \"文字與卡片物件邊界需融入『墨汁暈染（Ink Bleeding）』的漸層過渡效果，營造出彷彿墨跡在紙張纖維中自然擴散、虛實交織的立體層次\"\nvibes: \"冷靜、深邃、字字珠璣。將前沿技術的極致精準，收斂於古老東方的內斂美學中，令人聯想到當代水墨藝術展或高端多媒體數位藝廊\"\ncolor_palette:\nbackground: \"宣紙微黃 (Xuan White) 或 輕煙薄霧灰\"\ntext: \"松煙濃墨黑 (Pine Smoke Black) 或 枯筆淡墨灰\"\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 35\nprohibited_elements:\n- \"散文式的冗長贅字\"\n- \"情緒化的口語俚語\"\n- \"破壞留白感的密集資料堆砌\"\nwriting_style: \"冷靜、深邃、充滿哲學底蘊。行文節奏如大師揮毫，用字極其洗鍊，將硬核的深度學習術語與古典文學的行文韻律完美交織，直接以本質洞察說服聽眾\"\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 點睛破題（濃墨）：用一字千金的精煉陳述，如第一道濃墨直擊技術或議題的核心本質\"\n- \"2. 脈絡佈局（墨韻流動）：梳理底層架構或數據流，用具演進感的文字描述模組間的共振與解構\"\n- \"3. 虛實相生（細節與留白）：實處精準列出硬核指標與痛點，虛處以引用區塊延伸出引人深思的範式思考\"\n- \"4. 餘韻綿長（淡墨未來）：不給予封閉式的絕對結論，而是指出具前瞻性的延伸趨勢，留下寬廣的對話空間\"\n"
    },
    {
        "id": "style-1780793669053",
        "tag": "文青質感",
        "name": "📏手繪原稿插畫風格 (Hand-drawn Sketch & Illustration Style)",
        "description": "以粗糙的「重磅素描紙」為背景，採用自由奔放且不對稱的速寫佈局。文字與卡片邊緣呈現色鉛筆或麥克筆疊色的微透明層次，陰影由手繪斜線交織而成。整體充滿有機、不完美的創作者溫度，如同翻閱科學家的實驗筆記或動畫分鏡腳本，兼具知性與創造力。",
        "applicable": "概念發想、產品設計稿演示、技術架構拆解、科學實驗筆記、迭代藍圖說明",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：手繪原稿插畫風格 (Hand-drawn Sketch & Illustration Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Hand-drawn Sketch & Illustration Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"自由奔放的速寫佈局，排版帶有手稿的隨性與不對稱感，打破傳統網格的僵硬限制\"\nstyling:\ntactile_textures: \"背景呈現帶有粗糙顆粒感的『重磅素描紙（Heavyweight Sketchbook Paper）』或『輕質再生紙』，邊緣隱約可見鉛筆起草的淡灰色輔助線與毛邊\"\ndepth_effect: \"文字與卡片物件邊緣呈現『色鉛筆反覆疊色（Pencil Layering）』或『麥克筆疊塗』的微透明層次，卡片陰影則由密集的擬真手繪斜線（Hatching）交織而成\"\nvibes: \"充滿有機、不完美的創作者溫度，如同翻閱科學家的實驗筆記或動畫導演的動態分鏡腳本（Storyboard），兼具知性與創造力\"\ncolor_palette:\nbackground: \"象牙純質紙白 (Ivory Paper White) 或 復古牛皮紙褐\"\ntext: \"炭精筆深焦黑 (Charcoal Black) 或 普魯士藍手繪墨\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 42\nprohibited_elements: [\"生硬沉悶的法律條約式排版\", \"毫無修飾的數位預設字體感\", \"過度冷漠的官僚宣言\"]\nwriting_style: \"直白、具象、富有探險精神。如同設計師在白板上邊畫邊聊的互動感，善用生動的比喻與具體場景打破技術壁壘，語氣真誠且極具啟發性\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 靈感篝火（概念初繪）：從一個具體痛點的『第一道草圖』出發，勾勒出核心問題與探索起點\"\n- \"2. 結構解剖（線稿拆解）：如同工業設計透視圖般，將複雜的技術架構或數據流程拆解為清晰的手繪局部與邏輯線\"\n- \"3. 實證著色（色彩賦能）：用亮色調的手繪大方塊填入核心成果與關鍵指標，讓抽象的數據價值躍然紙上\"\n- \"4. 未完待續（藍圖延伸）：保留手稿邊緣未完成的延伸線條，象徵系統的持續演進，邀請聽眾加入未來的疊代旅程\"\n\n"
    },
    {
        "id": "style-1780795257476",
        "tag": "文青質感",
        "name": "🖇️中式書法狂草風格 (Chinese Wild Cursive Calligraphy Style)",
        "description": "狂放不羈的非對稱動態佈局。背景為生宣紙或絹帛的歲月紋理，局部穿插狂草飛白，搭配焦墨極致黑與硃砂落款紅。視覺強調枯筆焦墨層次，營造筆走龍蛇、氣勢磅礴的東方美學與立體力道。",
        "applicable": "戰略提案、趨勢分析、核心技術發布、高層匯報、重大變革宣言",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：中式書法狂草風格 (Chinese Wild Cursive Calligraphy Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Chinese Wild Cursive Calligraphy Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"大開大合、打破常規的縱向動態佈局，字裡行間如龍蛇飛舞，呈現氣勢磅礴的非對稱視覺節奏\"\nstyling:\ntactile_textures: \"背景帶有『手工生宣紙』或『粗織絹帛』的歲月紋理，局部穿插狂草獨有的『飛白（Flying White）』與潑墨乾枯對比的微米級實體質感\"\ndepth_effect: \"筆畫邊緣具備水分迅速被紙張吸乾的『枯筆焦墨層次』，重點物件伴隨『硃砂印章（Cinnabar Seal）』的微弱壓印下凹痕跡，營造墨跡入紙三分的立體力道\"\nvibes: \"狂放不羈、高能量、一氣呵成。將前沿技術的顛覆性力量，寄託於筆走龍蛇的東方線條美學中，令人聯想到當代前衛書法展或氣勢磅礴的交響樂章\"\ncolor_palette:\nbackground: \"歲月古紙黃 (Aged Parchment) 或 輕草灰\"\ntext: \"焦墨極致黑 (Charcoal Ink Black) 或 硃砂落款紅 (Cinnabar Red)\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 32\nprohibited_elements: [\"拘泥小節的逐條解釋\", \"毫無氣勢的平庸贅述\", \"死板對稱的框線約束\"]\nwriting_style: \"剛勁有力、氣勢如虹、字字珠璣。行文節奏大膽縱橫，將硬核科技核心提煉為具備情感張力與速度感的短句，直接以雷霆萬鈞的本質洞察震懾聽眾\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 揮毫落紙（亂象破局）：如狂草第一筆破空而來，以最辛辣、最深刻的痛點陳述，瞬間撕裂舊有格局\"\n- \"2. 筆走龍蛇（架構狂飆）：梳理核心技術的演進與爆發，用充滿流動感與速度感的線條隱喻，展現架構的縱橫交錯\"\n- \"3. 墨氣淋漓（硬核實證）：以飽滿、突出的硃砂紅色塊或巨型焦墨字體，甩出經得起時間考驗的震撼數據與核心成果\"\n- \"4. 意盡神遠（不羈未來）：收筆之處不設封閉框架，而是留下一道筆意未盡、具備強烈前瞻性的開放式思考，任由餘韻激盪\"\n\n"
    },
    {
        "id": "style-1780795591146",
        "tag": "文青質感",
        "name": "🆕 巴黎街頭時尚美學風格 (Parisian Street Fashion Aesthetics Style)",
        "description": "採用「Effortless Chic」排版，以高磅數未塗布紙或底片顆粒為背景。利用靈活留白、不對稱設計，搭配極簡細線框與高對比視覺落差，營造自信、慵懶且精準的高級訂製感，宛如頂級時尚雜誌內頁。",
        "applicable": "品牌策略提案、前沿技術介紹、高階設計審核、數據成果摘要",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：巴黎街頭時尚美學風格 (Parisian Street Fashion Aesthetics Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Parisian Street Fashion Aesthetics Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"經典、不費力的法式優雅（Effortless Chic）排版，刻意打破絕對對稱，利用靈活的留白與不對稱圖文呼應，傳達出鬆弛卻精準的高級訂製感\"\nstyling:\ntactile_textures: \"背景為帶有微細顆粒感的『高磅數未塗布紙（Uncoated Paper）』或『35mm底片復古顆粒質感』，物件邊緣乾淨俐落，彷彿頂級時尚雜誌的實體印刷內頁\"\ndepth_effect: \"文字與卡片邊界融入極致精細的『極簡細線框（Hairline Borders）』與輕微的『平面剪貼層次（Collage Depth）』，不使用重度漸層，而是靠高對比度的視覺落差營造低調的奢華感\"\nvibes: \"自信、極度精緻且毫不費力。將前沿技術的複雜硬核，收斂於慵懶且經典的時裝美學之中，令人聯想到巴黎時裝週外的精緻街拍或當代精品藝廊\"\ncolor_palette:\nbackground: \"經典風衣米白 (Trench Beige) 或 暮光冷石灰\"\ntext: \"高級訂製深邃黑 (Couture Black) 或 慵懶波爾多紅 (Bordeaux Red)\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 36\nprohibited_elements: [\"毫無個性的公式化贅詞\", \"廉價過時的口號標語\", \"破壞整體高冷感的密集表格\"]\nwriting_style: \"精準而克制、優雅而自信。行文如同時尚評論家般犀利，字字點到為止，拒絕平鋪直敘的冗長解釋，直接用最犀利的觀點與洗鍊的修辭震懾觀眾\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 街頭初見（經典序幕）：以最具反差感的核心痛點切入，如同走在香榭大道被一抹經典造型瞬間吸引，直擊問題本質\"\n- \"2. 高級剪裁（結構重塑）：如同高訂服裝的精準打版，將複雜的技術或商業模型進行完美拆解，只保留最具靈魂的骨架與線條\"\n- \"3. 天橋盛宴（硬核高潮）：用對比強烈、比例完美的精緻方塊，大膽展示無可挑剔的數據成果與最亮眼的關鍵核心指標\"\n- \"4. 經典不敗（風格延伸）：不給予平庸的封閉式結論，而是留下一個引人玩味、超越潮流的前瞻趨勢，讓優雅餘韻持續發酵\"\n\n"
    },
    {
        "id": "style-1780795758097",
        "tag": "活力數位",
        "name": "🆕 兒童粗蠟筆塗鴉風格 (Children's Thick Crayon Doodle Style)",
        "description": "背景是粗糙纖維感的圖畫紙，圖文採自由非線性排版，帶有童趣的輕微歪斜感。視覺由厚重、不均勻的粗蠟筆堆疊蠟質與筆屑痕跡構成，色塊呈現筆觸反覆塗抹的手工疊色效果，營造熱情奔放且富有直覺想像力的風格。",
        "applicable": "創意發想與提案、複雜概念簡化教學、初期研究成果發表、專案啟動簡報",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：兒童粗蠟筆塗鴉風格 (Children's Thick Crayon Doodle Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Children's Thick Crayon Doodle Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 擺放與視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry: grid: \"純真、不受拘束的自由非線性排版，圖文呈現自然錯落，帶有童趣的輕微歪斜與不對稱感\"\nstyling: tactile_textures: \"背景為帶有明顯粗糙纖維感的『八開白色圖畫紙（Drawing Paper）』，物件與文字邊緣具備厚重、不均勻的『粗蠟筆堆疊蠟質（Thick Crayon Wax）』與細微的筆屑痕跡\"\ndepth_effect: \"色塊與卡片呈現筆觸反覆塗抹、不完全飽和的『手工疊色效果』，陰影由粗蠟筆線條隨意橫劃的『排線重疊（Overlay Sketching）』組成，營造純物理的手作厚實度\"\nvibes: \"充滿童心、熱情奔放且富有直覺想像力。用不造作的純真視角簡化複雜世界，令人聯想到兒童繪畫展或充滿創意的塗鴉實驗室\"\ncolor_palette: background: \"溫暖圖畫紙白 (Sketchpad White) 或 太陽暖黃\" text: \"蠟筆濃炭黑 (Crayon Black) 或 飽和深海藍\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 38\nprohibited_elements: [\"晦澀難懂的學院派公式\", \"死板空洞的官僚文字\", \"毫無生氣的冷酷數據表格\"]\nwriting_style: \"直覺、純粹、富含聯想力。如同用孩子的眼睛看世界，將複雜的架構轉譯為最具象、好懂的『積木與玩具隱喻』，語氣真誠熱切，直接用最底層的本質打動聽眾\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n\"1. 好奇心的起點：從一個最根本、最直覺的提問出發，打破既定思維，大膽揭示核心痛點\"\n\"2. 積木大拆解：將複雜的技術模型或業務流程，拆解成最基礎、最容易理解的『基礎元件構造』\"\n\"3. 神奇玩具箱：用鮮豔、醒目的巨型蠟筆色塊，展示最具驚喜感與破壞力的數據成果與應用價值\"\n\"4. 下一站太空船：以充滿希望與想像力的筆觸勾勒出未來的演進方向，邀請聽眾攜手展開下一段冒險旅程\"\n\n"
    },
    {
        "id": "style-1780795954911",
        "tag": "商務科技",
        "name": "🆕 金融數據專家風格 (Financial Data Expert Style)",
        "description": "強調嚴謹的多維格線系統與資本市場效率。背景具高級財報壓紋或彭博終端像素網格，圖表邊緣帶有高頻電子看板微發光感。配色為深邃藍/石墨灰搭配增長翠綠/古銅金，風格極度理性沉穩。",
        "applicable": "量化投資策略報告、宏觀經濟分析、財報與壓力測試簡報、資產安全邊際報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：金融數據專家風格 (Financial Data Expert Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Financial Data Expert Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 簡報視覺佈局约束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"矩陣式、極度嚴謹的多維數據格線系統，強調資本市場的秩序、流動性與極致效率\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有高級實體財報的『重磅防偽浮水印壓紋紙』質感，或彭博終端機（Bloomberg Terminal）特有的『微米級暗色電子像素網格』\"\ndepth_effect: \"數據圖表、K線指標與卡片物件邊界需融入『高頻電子看板』的微發光切面，或精細的『雷射防偽標籤』微幅凹凸層次，營造出資訊即時跳動與高價值資產的實體厚重感\"\nvibes: \"絕對理性、沉穩、具備掌控億級資本的決策分量。將瞬息萬變的市場波動收斂於無懈可擊的數學模型中，令人聯想到華爾街頂級對沖基金總部或瑞士私人銀行決策室\"\ncolor_palette:\nbackground: \"彭博終端深邃藍 (Terminal Navy) 或 華爾街冷石墨灰\"\ntext: \"資本增長翠綠 (Growth Green) 或 條金古銅金\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 42\nprohibited_elements: [\"空泛的市場營銷話術\", \"未經量化的主觀預測\", \"情緒化的驚嘆與誇大修飾\"]\nwriting_style: \"犀利、數據導向、具備極高信噪比。語氣沉穩且充滿市場權威感，用詞精確洗鍊，拒絕含糊的形容詞，直接以複利、夏普值（Sharpe Ratio）等硬核指標與量化因果進行邏輯說服\"\n\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n\"1. 市場宏觀定錨（Alpha 起源）：剖析當前宏觀經濟痛點、波動率或套利機會，以絕對客觀的市場事實定錨核心議題\"\n\"2. 量化模型架構（因子拆解）：如同資產定價模型，將複雜數據流拆解為底層的核心驅動因子、演算法與風險控管邏輯\"\n\"3. 壓力測試實證（資產負債表）：用剛性、高對比的數據方塊，甩出經得起歷史回測（Backtesting）與極限壓力測試的量化成果\"\n\"4. 風險邊際永續（終局策略）：重申資產安全邊際、最大回撤控制（Drawdown Control）與長期價值增長的前瞻演進藍圖\"\n\n"
    },
    {
        "id": "style-1780796523396",
        "tag": "文青質感",
        "name": "🆕 暖心繪本敘事風格 (Warning Heart Narrative Style)",
        "description": "自由有機的非對稱佈局，搭配手繪水彩紙紋理和色鉛筆觸感。視覺溫暖治癒，利用柔焦陰影和層疊，營造微縮模型般的立體繪本空間感，充滿詩意與魔幻寫實。",
        "applicable": "品牌故事、年度回顧、願景發布、企業文化傳達、公益活動報告、啟發性演講",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：暖心繪本敘事風格 (Warning Heart Narrative Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Warning Heart Narrative Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"🎨 \n\n\n2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"自由、有機且富有故事感的非對稱佈局，文字與圖案留白交織，如同翻閱一本精緻的成人繪本\"\nstyling:\ntactile_textures: \"背景呈現細緻的『手繪水彩紙紋理（Watercolor Paper Grain）』，邊緣帶有淡淡的色鉛筆筆觸或輕微的毛邊感，拒絕死板的數位平塗\"\ndepth_effect: \"物件與文字微顯層疊，利用溫和的半透明光影與微弱的柔焦陰影，營造出彷彿『微縮模型（Mitate Miniature）』或立體繪本般的空間錯置感\"\nvibes: \"溫暖治癒、帶著一絲帶有詩意的孤獨與魔幻寫實。在宏大的日常場景中聚焦微小個體，激發情感共鳴與童心\"\ncolor_palette:\nbackground: \"夢幻暮光藍 (Twilight Blue) 或 溫暖繪本米黃\"\ntext: \"深夜手繪墨藍 (Midnight Ink) 或 森林深處綠\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 40\nprohibited_elements: [\"冰冷沉悶的商業教條\", \"過度堆砌的技術黑話\", \"毫無情感的純數據條列\"]\nwriting_style: \"富有詩意、獨白式的敘事語氣。將生硬的資訊轉化為帶有溫度、啟發性的故事線，用詞溫柔而深刻，點到為止，留給觀眾想像與感悟的空間\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n\"1. 遇見與迷惘：以都市或星空為隱喻，點出目前面臨的核心痛點或未知挑戰\"\n\"2. 微觀新視界：將視角縮小，像 1:87 的微縮世界般，專注剖析被忽略的關鍵技術細節或核心概念\"\n\"3. 溫暖的光點：將數據成果或解決方案轉化為旅程中遇見的驚喜，用具象、溫暖的大方塊承載核心價值\"\n\"4. 擁抱未知的旅程：重申願景，不給予生硬的終點，而是以開放且充滿希望的前瞻視角，邀觀眾一同前行\"\n\n"
    },
    {
        "id": "style-1780796719850",
        "tag": "麥肯錫高階",
        "name": "🆕 精密機械專家風格 (Precision Machinery Expert Style)",
        "description": "極致精準的工程幾何格線，背景為陽極氧化鋁或碳纖維質感。文字物件具CNC精密倒角與雷射雕刻線，營造組件嚴密互鎖的物理深度。風格冰冷、強悍、精確，配色為鈦金屬灰/深邃藍與冷光藍/安全橘。",
        "applicable": "技術規格報告、工程分析報告、品質控制報告、系統架構簡報、量化數據報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：精密機械專家風格 (Precision Machinery Expert Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Precision Machinery Expert Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"極致精準、微米級對稱的工程幾何格線系統，遵循嚴格的藍圖秩序，傳達零誤差的工業美學\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有航太級『陽極氧化鋁（Anodized Aluminum）』、微型『鈦合金蝕刻微線路』或輕量化『碳纖維編織（Carbon Fiber）』的微米級硬核實體質感\"\ndepth_effect: \"文字與卡片物件邊界展現出如同『CNC 數控銑削』的精密倒角（Chamfers）與階梯式凹槽，搭配極細的『雷射雕刻輔助線（Laser-etched Calibrations）』，營造出組件嚴密咬合與互鎖的多層次物理深度\"\nvibes: \"冰冷、強悍、極致精確且無懈可擊。將一切混亂轉化為可預測的齒輪嚙合與電路邏輯，令人聯想到半導體光刻機內部架構或瑞士頂級機械錶芯\"\ncolor_palette:\nbackground: \"航太鈦金屬灰 (Titanium Grey) 或 晶圓深邃藍\"\ntext: \"雷射冷光藍 (Laser Blue) 或 儀表板安全橘\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 60\nprohibited_elements: [\"模糊不清的概括形容\", \"感性非理性的情緒推論\", \"破壞系統精密度的雜亂無序排版\"]\nwriting_style: \"嚴謹、冷靜、高度結構化。字句如精密儀器產出的標定數據，用字精確至極，拒絕任何灰色地帶，直接以無懈可擊的邏輯推導與硬核因果關係說服觀眾\"\n\n\n📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 基準點校正（誤差溯源）：明確認定系統初始狀態與核心公差限制，直擊阻礙效率與穩定性的底層痛點\"\n- \"2. 動態傳動架構（核心解構）：將複雜系統拆解為高效嚙合的模組，剖析核心演算法與高精度控制流程\"\n- \"3. 額定效能實證（應力測試）：以剛性大方塊配合精密儀表數據，甩出經得起極限應力測試的量化指標與成果\"\n- \"4. 零故障願景（持續疊代）：定義長效穩定運作的封閉控制迴路（Closed-loop），提供具備高度可預測性的演進路徑\"\n\n"
    },
    {
        "id": "style-1780797576360",
        "tag": "活力數位",
        "name": "🆕 醜陋塗鴉風格 (Ugly Graffiti & Brutalist Doodle Style)",
        "description": "採用刻意不對稱的反設計佈局，背景使用街頭水泥牆或褶皺報紙等粗糙質感。物件以粗黑麥克筆重描邊和硬邊塊狀陰影，營造出叛逆、高能量且極具視覺衝擊",
        "applicable": "顛覆性創新提案、高衝突的市場痛點分析、反傳統策略報告、文化改革倡議",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：醜陋塗鴉風格 (Ugly Graffiti & Brutalist Doodle Style)\n==========================================\n\nstyle_config:\ntheme_name: \"Ugly Graffiti & Brutalist Doodle Style\"\nversion: \"2026.1\"\n\n\n🛠️ 1. 簡報基本資訊\n\npresentation_info:\ntitle: \"打破常規：顛覆性創新與反叛思維\"\ntarget_pages: \"5\"\nlanguage: \"zh-TW\"\n\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n\nvisual_constraints:\ngeometry:\ngrid: \"刻意不對稱、歪斜且帶有衝突感的反設計（Anti-design）佈局，物件隨性重疊，打破一切常規格線\"\nstyling:\ntactile_textures: \"背景呈現帶有粗糙顆粒的『街頭水泥牆面』、被揉爛的『褶皺報紙』或『回收瓦楞紙板』質感，充滿未經加工的粗糙與原始感\"\ndepth_effect: \"文字與卡片物件使用『粗黑麥克筆重描邊（Hard Stroke）』，搭配完全沒有模糊半徑的『硬邊塊狀純黑陰影（Solid Drop Shadows）』，營造出強烈、甚至帶有刺眼感的手繪拼貼層次\"\nvibes: \"叛逆、高能量、未經修飾且極具視覺衝擊。如同地下樂團的 zine（獨立小報）或街頭塗鴉牆，用不完美的野性打破大企業的精緻偽裝\"\ncolor_palette:\nbackground: \"瓦楞紙屑褐 (Cardboard Brown) 或 街頭暴動水泥灰\"\ntext: \"噴漆極致死黑 (Graffiti Black) 或 螢光有毒綠 (Toxic Neon Green)\"\n\n\n✍️ 3. 內容精簡與文案規則 (Text Rules)\n\ncontent_rules:\nword_count_limit_per_slide: 30\nprohibited_elements: [\"虛偽溫和的客套修飾\", \"平庸無奇的官僚匯報\", \"對稱工整的排版美學\"]\nwriting_style: \"銳利、直白、帶有挑釁與諷刺感的幽默語氣。直接撕開企業黑話的糖衣，用最粗暴但一針見血的動詞直擊底層邏輯，話語充滿野蠻生長的生命力\"📑 4. 簡報推進邏輯 (Slide Flow)\n\nflow_logic:\nsequence:\n- \"1. 砸碎現狀（痛點引爆）：用最挑釁的提問或震撼事實，一棒敲碎市場的集體盲點與假象\"\n- \"2. 混亂核心（底層真相）：撕開漂亮的架構圖，直接展示最真實、未經美化的核心技術缺陷或市場本質\"\n- \"3. 野蠻生長（瘋狂實證）：用粗暴、醒目的巨型螢光色方塊，甩出經得起拷問的硬核數據與顛覆性成果\"\n- \"4. 朋克不死（持續顛覆）：拒絕給出安穩的傳統結論，而是拋出一個具備煽動性的前瞻議題，挑動聽眾的既有認知\"\n\n"
    },
    {
        "id": "style-1781168640686",
        "tag": "活力數位",
        "name": "🆕 校園青春活潑風格 (Campus Youthful & Lively Style)",
        "description": "採用非對稱對角線格線系統，搭配元氣奶黃或薄荷綠背景，並融入紙膠帶邊緣、手繪螢光筆筆觸與拍立得相紙重疊的柔和軟陰影，營造出朝氣蓬勃且具手作海報剪貼感的立體躍動視覺深度 。",
        "applicable": "黑客松決賽提案、校園創意市集企劃、學生社團發表會報告、科技創新創意實踐報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：校園青春活潑風格 (Campus Youthful & Lively Style)\n==========================================\nstyle_config:\ntheme_name: \"Campus Youthful & Lively Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"動態跳躍、充滿能量的非對稱對角線格線系統，打破死板框架，傳達青春無畏的探索節奏\"\nstyling:\ntactile_textures: \"背景呈現高磅數『塗佈原紙（Coated Paper）』或復古『拍立得相紙』的平滑細緻感，局部飾以微米級的『紙膠帶邊緣』、手繪『螢光記號筆筆觸』或校園徽章的霧面實體質感\"\ndepth_effect: \"文字與卡片物件使用如同『拍利得照片重疊』或『手作海報剪貼（Collage）』的柔和軟陰影（Soft Drop Shadows），營造出層次分明、充滿立體躍動感的視覺深度\"\nvibes: \"朝氣蓬勃、高能量、充滿無窮想像力與感染力。將前沿科技的硬核邏輯，轉譯為充滿社群活力的熱血提案，令人聯想到黑客松（Hackathon）決賽舞台、校園創意市集或熱血的社團發表會\"\ncolor_palette:\nbackground: \"活力元氣奶黃 (Vibrant Cream) 或 汽水薄荷綠\"\ntext: \"夜校極客深海藍 (Geek Navy) 或 朝氣盛夏熱力橘\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"老氣沉悶的八股教條\", \"陳腐死板的官方套話\", \"毫無生氣且缺乏節奏的純數據堆砌\"]\nwriting_style: \"熱情、具備高渲染力、直率且富有前瞻性。善用極具畫面感的校園生活或社群隱喻打破技術壁壘，字句精準爽快、富有節奏感，直接用真實的熱忱與清晰的邏輯結構打動聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 青春敲門磚（靈感碰撞）：從一個打破常規的校園痛點或瘋狂點子出發，大膽揭示核心挑戰與探索起點\"\n- \"2. 社群大作戰（熱血架構）：將複雜的系統或數據邏輯，轉化為並肩作戰的模組分工，建立清晰活潑的解題模型\"\n- \"3. 成果發表會（高燃實證）：用色彩鮮明、比例醒目的元氣大方塊，甩出經得起嚴格考驗的高燃數據與硬核成果\"\n- \"4. 奔向下一站（無限未來）：不設死板的標準結局，而是以開放、熱切且充滿希望的視野勾勒未來演進藍圖，邀請大家一同加入這場科技冒險\"\n"
    },
    {
        "id": "style-1781169603055",
        "tag": "商務科技",
        "name": "🆕 數位高科技風格 (Digital High-Tech & Cyber-Grid Style)",
        "description": "本風格採用矩陣式多維度數位網絡系統，以暗藍或賽博深夜黑為背景，融合OLED微米級發光像素點陣與全息光柵紋理。物件具備毛玻璃半透明折射層次，搭配霓虹向量雷射邊框與外發光疊加，打造出資訊懸浮於虛擬空間的立體全息深度與極客美學張力。",
        "applicable": "科技巨頭全球開發者大會簡報、AI技術奇異點控制室報告、高維數據視覺化分析、生成式AI與數位生態系架構演進報告、前瞻技術範式轉移實證。",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：數位高科技風格 (Digital High-Tech & Cyber-Grid Style)\n==========================================\nstyle_config:\ntheme_name: \"Digital High-Tech & Cyber-Grid Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"矩陣式、多維度的數位網絡系統，融合動態拓撲圖（Topology Map）與點線節點（Node-Link）佈局，傳達無縫連接與光速運算的未來感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有『OLED 微米級發光像素點陣（Micro-LED Matrix）』、『全息光柵透鏡紋理（Holographic Grating）』或『微晶片矽晶圓導線軌跡（Silicon Wafer Traces）』的純數位實體質感\"\ndepth_effect: \"文字與卡片物件邊界融入高科技的『毛玻璃半透明（Glassmorphism）』折射層次，搭配極細的『霓虹向量雷射邊框（Neon Vector Borders）』與微幅的『外發光（Outer Glow）』疊加，營造出資訊懸浮於虛擬空間的立體全息深度\"\nvibes: \"前衛、高擬真（High-Fidelity）、充滿極客（Geek）美學與數位張力。將冰冷的二進位數據轉化為璀璨的資訊流，令人聯想到頂級科技巨頭的全球開發者大會（Developer Keynote）、AI 奇異點控制室或高維數據視覺化空間\"\ncolor_palette:\nbackground: \"數位賽博深夜黑 (Cyber Midnight Black) 或 矩陣深邃暗藍\"\ntext: \"光子量子螢光藍 (Quantum Teal) 或 萬物互聯極客白\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"空泛感性的唯美修辭\", \"傳統保守的行政官僚套話\", \"缺乏科技含量的冗長敘事\"]\nwriting_style: \"銳利、前瞻、充滿未來感與極致理性。字句如同編譯完成的底層代碼（Compiled Code），用字精確且具破壞性創新力，拒絕模糊空間，直接以技術制高點、演算法邏輯與數據因果說服觀眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 系統初始化（核心痛點編譯）：從一個最具顛覆性的底層 Bug、技術瓶頸或範式轉移出發，光速破譯既有市場的致命盲點\"\n- \"2. 演算法解構（高維技術架構）：將核心模型、多模態管道（Pipelines）或數位資產流拆解為高效率的點線拓撲結構，清晰展示資訊的高速流轉\"\n- \"3. 算力全面爆發（數據與奇異點實證）：用高對比、自發光的矩陣色塊與高亮代碼塊，甩出經得起極端並發（Concurrency）測試的震撼量化數據與硬核成果\"\n- \"4. 全息演進未來（生態無限擴展）：拒絕給予封閉停滯的結論，而是開啟一個持續自我疊代（Self-Iterating）、具備無限動態擴展可能的數位新藍圖\"\n"
    },
    {
        "id": "style-1781169803366",
        "tag": "活力數位",
        "name": "🆕 專業運動競技風格 (Professional Sports & Athletic Competition Style)",
        "description": "視覺背景採用曜石深灰或鈦金黑，融入碳纖維顆粒與網布質感，結合高對比背光與動態殘影。排版透過不對稱動態格線與大膽傾斜切割線，搭配螢光黃或耀眼金字體，展現極致專注、紀律嚴明與強烈速度感。",
        "applicable": "競技數據分析報告、系統效能優化報告、高強度系統疊代報告、極限壓力測試報告、技術競爭力與戰術分析報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：專業運動競技風格 (Professional Sports & Athletic Competition Style)\n==========================================\nstyle_config:\ntheme_name: \"Professional Sports & Athletic Competition Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"強調爆發力與速度感的不對稱動態格線系統，融入大膽的傾斜切割線與力量感排版，傳達毫秒必爭的競技節奏\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有高科技田徑場『碳纖維跑道顆粒』、頂級運動裝備『編織網布（Flyknit）』或『霧面防滑橡膠（Matte Grip Rubber）』的微米級高抓地實體質感\"\ndepth_effect: \"文字與卡片物件邊界融入『高對比衝擊背光（High-contrast Backlighting）』或『碳纖維立體壓紋』，搭配極具速度感的『動態殘影切面』，營造出破風前行、極具破壞力的物理立體感\"\nvibes: \"充滿爆發力、極致專注、追求極限且紀律嚴明。將數據與架構視為贏得比賽的戰術板，令人聯想到一級方程式賽車（F1）維修區、奧運百米決賽舞台或頂級職業球隊的極限訓練室\"\ncolor_palette:\nbackground: \"賽道曜石深灰 (Racetrack Charcoal) 或 科技鈦金黑\"\ntext: \"破風螢光黃 (Volt Neon) 或 冠軍耀眼金 (Podium Gold)\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"拖泥帶水的冗長鋪陳\", \"毫無鬥志的消極修飾\", \"破壞高節奏運動感的散漫排版\"]\nwriting_style: \"剛勁、果斷、高張力、絕對目標導向。行文節奏如爆發力十足的短跑，用字如同主教練精準的戰術指令，拒絕任何灰色地帶，直接以勝率、突破極限、數據碾壓的因果推導震懾觀眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 鳴槍起跑（極限挑戰）：精準鎖定核心瓶頸或競爭對手的致命威脅，以破釜沉舟的競技姿態定錨起跑線\"\n- \"2. 戰術板拆解（高強度架構）：如同在賽前拆解對手攻防，將複雜技術或演算法模型拆解為最高效、零冗餘的致勝核心組件\"\n- \"3. 冠軍計時（毫秒實證）：用剛性、高亮度的數據方塊與速度指標，甩出經得起嚴格極限測試的碾壓性成果與紀錄\"\n- \"4. 榮耀終點線（極限永續）：不給出安穩的傳統結論，而是瞄準下一個更高、更快、更強的里程碑，持續推動系統的高強度疊代\"\n"
    },
    {
        "id": "style-1781576903349",
        "tag": "麥肯錫高階",
        "name": "026-專業教育風格 (Professional Educational Pedagogy Style)",
        "description": "本風格採用條理分明的鷹架式格線系統，背景具備厚實再生卡紙與微磨砂幾何模型質感，搭配微弱層級壓痕與粉筆邊線，營造教科書般的物理深度，並以溫潤米白或學院深綠結合灰黑或石墨藍文字，展現嚴謹且具啟發性的教學工藝氛圍 。",
        "applicable": "學科概念建立報告、評量效度分析報告、翻轉課堂教學計畫、國際學術研討會發表、教育心理學實驗室成果匯報、核心素養導向教學成果報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：專業教育風格 (Professional Educational Pedagogy Style)\n==========================================\nstyle_config:\ntheme_name: \"Professional Educational Pedagogy Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"條理分明、層次清晰的鷹架式（Scaffolding）格線系統，強調知識傳遞的循序漸進與認知邏輯的安定感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有高級教具特有的『厚實再生卡紙』、微細纖維的『經典高密度黑板/白板』或輕微磨砂的『壓克力幾何幾何模型』實體質感\"\ndepth_effect: \"知識圖表與教學卡片物件需融入微弱的『層級壓痕（Debossing）』與『粉筆/標籤邊線』，營造出如同教科書重點編輯、考卷測驗結構般層層堆疊且清晰好懂的物理深度\"\nvibes: \"充滿教育熱忱、嚴謹且極具啟發性。將硬核複雜的抽象技術與理論，收斂於兼具認知心理學與教學工藝的結構中，令人聯想到頂尖翻轉課堂、國際學術研討會或教育心理學實驗室\"\ncolor_palette:\nbackground: \"經典溫潤校園米白 (Campus Ivory) 或 學院深沉綠\"\ntext: \"知識粉筆灰黑 (Pedagogy Charcoal) 或 學術石墨藍\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"流於形式的空泛口號\", \"未經轉譯的冰冷黑話\", \"打斷認知流的無效視覺雜訊\"]\nwriting_style: \"專業、循循善誘、結構嚴密。語氣散發著無懈可擊的信任感與引導者的智慧，善用兼具嚴謹度與直覺性的『認知鷹架』和『具象隱喻』，用字精確洗鍊，直接以邏輯因果與實證說服觀眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 引起動機與起點行為（迷惘溯源）：從一個核心的認知衝突、教學痛點或試題盲點出發，定錨學習或研究起點\"\n- \"2. 概念發展與結構解構（認知鷹架）：將複雜的硬核理論或數據流，拆解為高度結構化的核心組件，建立清晰的邏輯模型\"\n- \"3. 歷程實證與效度分析（形成性評量）：用穩健、高對比的數據大方塊與信度指標，展示經得起考驗的量化成果與實證效益\"\n- \"4. 遷移與永續發展（總結性願景）：重申長期核心素養的建立、系統疊代與知識遷移的前瞻藍圖，留下深遠的思考空間\"\n"
    },
    {
        "id": "style-1781577320625",
        "tag": "活力數位",
        "name": "027-復古 8-bit 像素風格 (Retro 8-bit Pixel Style)",
        "description": "本風格採用嚴格等距的8-bit像素網格系統，背景融入CRT映像管螢幕的水平掃描線與螢光粉電子顆粒質感 。物件與文字搭配直角階梯狀的像素厚度與硬邊落差陰影，並以深邃黑或暗夜藍背景襯托高能發光像素綠或金黃色澤，營造極具高能量電子感的懷舊街機美學 。",
        "applicable": "遊戲化機制提案、前沿科技演算法展示、懷舊文化與電玩產業分析報告、晶片音樂派對與次文化活動企劃、資訊工程與極客主題簡報",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：復古 8-bit 像素風格 (Retro 8-bit Pixel Style)\n==========================================\nstyle_config:\ntheme_name: \"Retro 8-bit Pixel Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"嚴格、等距的 8-bit 像素網格系統（Grid System），帶有早期街機與家用主機的點陣化物理秩序感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有傳統 CRT 映像管螢幕特有的『水平掃描線（Scanlines）』、微微的『螢光粉電子顆粒』或復古街機外殼的『粗顆粒機體塑料』質感\"\ndepth_effect: \"物件與文字使用完全無模糊、直角階梯狀的『像素厚度（Pixel Extrusion）』與『1-bit 像素硬邊落差陰影』，搭配如同『低解析度點陣發光』的層次效果，營造復古硬體的分量感\"\nvibes: \"懷舊、極具高能量電子感、充滿街機黃金時代的極客（Geek）氣息。將冷峻的前沿科技收斂於 80 年代的像素美學中，令人聯想到懷舊電玩展、晶片音樂（Chiptune）派對或早期個人電腦終端\"\ncolor_palette:\nbackground: \"復古終端深邃黑 (Terminal Black) 或 街機暗夜藍\"\ntext: \"高能發光像素綠 (Neon Arcade Green) 或 8-bit 耀眼金黃\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"現代高畫質流於表面的陰影處理\", \"空洞乏味的企業官宣八股文\", \"打斷 8-bit 秩序的圓角與複雜漸層\"]\nwriting_style: \"精準、帶著一絲冷幽默的極客思維。字句如早期遊戲對話框中的捲動文本（Scroll Text），字字珍貴且毫無冗贅，將深奧的演算法或商業邏輯簡化為高含金量的遊戲化機制陳述\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. INSERT COIN（盲點投幣）：以最具衝擊力的核心痛點或市場亂象作為第一關，引爆硬核破局工作流\"\n- \"2. LEVEL 1（核心架構拆解）：如同遊戲關卡地圖，將複雜的數據流或技術架構拆解為一目了然的像素級積木組件\"\n- \"3. HIGH SCORE（硬核實證）：用大體積、高對比的發光像素方塊，強勢甩出經得起拷問的量化成果與核心數據指標\"\n- \"4. CONTINUED?（終局演進）：不給予傳統封閉式結論，而是留下一個引人玩味的『NEXT LEVEL』前瞻預告，為未來疊代預留思考空間\"\n"
    },
    {
        "id": "style-1781577529511",
        "tag": "文青質感",
        "name": "028-日系手繪插畫風格 (Japanese Hand-drawn Illustration & Miniature Style)",
        "description": "富含日式留白美學的非對稱佈局，背景融合溫潤和紙與重磅水彩紙的植物纖維紋理，邊緣帶有色鉛筆溫柔筆觸與水彩暈染痕跡。物件透過半透明層疊與柔焦鏡頭景深，營造出1:87微觀世界般的精巧立體層次，充滿細膩的職人手作溫度。風格美學調性與適合的主題場域。",
        "applicable": "微縮藝術展覽企劃、動畫手繪分鏡原稿發表、日常生活觀察報告、前瞻性技術轉譯簡報、富含情感溫度的職人故事與商務邏輯分享",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：日系手繪插畫風格 (Japanese Hand-drawn Illustration & Miniature Style)\n==========================================\nstyle_config:\ntheme_name: \"Japanese Hand-drawn Illustration & Miniature Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"輕盈、富有呼吸感與日式『留白（Ma）』美學的非對稱佈局，圖文交織散發細膩的日常節奏\"\nstyling:\ntactile_textures: \"背景呈現溫潤的手工『和紙（Washi）』或『重磅手繪水彩紙』微米級植物纖維紋理，邊緣帶有色鉛筆的溫柔筆觸與淡淡的水彩擴散暈染痕跡\"\ndepth_effect: \"物件與文字具備精緻的『微縮模型感（Mitate Miniature）』，利用溫和的半透明層疊與微弱的柔焦鏡頭景深（Tilt-shift effect），營造出彷彿 1:87 微觀世界般的精巧立體層次\"\nvibes: \"清新治癒、細膩且充滿職人手作溫度。在宏大的技術背景中聚焦微小而深刻的個體連結，令人聯想到當代日系微縮藝術展或經典動畫的手繪分鏡原稿\"\ncolor_palette:\nbackground: \"溫潤和紙白 (Washi White) 或 靜謐天空淡藍\"\ntext: \"日染靛青藍 (Indigo Blue) 或 宇治抹茶深綠\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"冰冷生硬的教條宣示\", \"華而不實的誇大修飾\", \"打斷溫暖敘事流的無效文字堆砌\"]\nwriting_style: \"溫柔、細膩且富含深刻洞察。行文如同一位兼具理性的職人與你並肩散步、娓娓道來，將繁複的演算法或邏輯轉譯為具備情感溫度的生活隱喻，字句精煉，直接以本質打動人心\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 日常的觀察（迷惘溯源）：從微小的生活場景或日常痛點切入，大膽揭示核心挑戰與探索的起點\"\n- \"2. 微觀大解構（線稿透視）：像微縮模型般將複雜的技術架構或數據流程，拆解為精巧、易懂的局部組件與溫暖脈絡\"\n- \"3. 拾獲的光芒（硬核實證）：用溫暖、色彩溫潤的水彩大方塊，展示經得起考驗的量化數據與核心成果\"\n- \"4. 迎向未來的晴空（前瞻願景）：不給予生硬的終點，而是以充滿希望與前瞻性的開放式藍圖，邀觀眾一同展開持續疊代的旅程\"\n"
    },
    {
        "id": "style-1781577733806",
        "tag": "活力數位",
        "name": "029-簡約鉛筆線條風格 (Minimalist Pencil Sketch & Drafting Style)",
        "description": "此風格以細紋素描紙為背景，保留極淡的幾何輔助線與微弱炭跡，展現手稿推演的真實感。完全摒棄數位陰影與漸層，物件邊界僅以雙線並行、單邊硬線或45度斜線排線表現投影，營造機械製圖般的二維線稿立體感，呈現冷靜、洗鍊且純粹的視覺氛圍。",
        "applicable": "建築設計提案、工業設計概念藍圖、科學技術手稿研究、系統架構解構報告、前衛實驗室成果匯報",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：簡約鉛筆線條風格 (Minimalist Pencil Sketch & Drafting Style)\n==========================================\nstyle_config:\ntheme_name: \"Minimalist Pencil Sketch & Drafting Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"極簡、輕量化的不對稱結構線系統，如同建築師的空白繪圖板，利用大膽的幾何留白與對齊導線，傳達極高資訊信噪比與理性秩序\"\nstyling:\ntactile_textures: \"背景為帶有微細物理顆粒的『輕量細紋素描紙（Fine-grain Sketch Paper）』或高檔肯特紙，畫面上局部隱約留有起草時的『H級極淡幾何輔助線』與輕微橡皮擦拭的微弱炭跡，彰顯純手稿推演的真實感與思維疊代痕跡\"\ndepth_effect: \"完全摒棄數位的模糊重陰影與漸層。卡片與區塊邊界僅以『0.5mm 雙線並行（Double-line Outlines）』、單邊硬線或細密的『45度物理斜線排線（Cross-Hatching）』來表現投影，營造出如同機械製圖、二維線稿的立體空間錯覺\"\nvibes: \"冷靜、洗鍊、純粹。剝離一切流於表面的色彩干擾，專注於思想的骨架與技術的底層邏輯，令人聯想到達文西的科學手稿、頂級建築師的概念藍圖或前衛的工業設計實驗室\"\ncolor_palette:\nbackground: \"冷感繪圖紙白 (Drafting White) 或 輕度素描骨灰\"\ntext: \"2B石墨深灰 (Graphite Grey) 或 針筆精準黑\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"任何形式的色彩平塗區塊\", \"含糊不清的形容詞堆砌\", \"破壞簡約線條感的複雜數據圖表外框\"]\nwriting_style: \"極度洗鍊、冷靜且富含邏輯硬度。行文如同總工程師在藍圖邊緣留下的精確註記，以『核心動詞＋量化指標』為主要骨架，字字珠璣，拒絕任何情感渲染，直接用無懈可擊的結構化因果關係說服觀眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 第一道線條（核心溯源）：從空白中拉出最關鍵的一條軸線，精準點破當前系統、市場或技術的核心痛點與基本假設\"\n- \"2. 骨架透視（架構解構）：如同立體透視圖（Perspective View），將複雜的硬核技術或數據流拆解為最本質的幾何線條與邏輯組件\"\n- \"3. 局部放大（硬核實證）：利用精細的線條大方塊或排線標註，聚焦並強勢甩出經得起時間拷問的量化指標、關鍵成果與數據成果\"\n- \"4. 延伸藍圖（前瞻演進）：不給予封閉、僵化的傳統結論，而是保留線條末端的延伸箭頭，勾勒出具備高度可預測性與疊代空間的未來藍圖\"\n"
    },
    {
        "id": "style-1781577977701",
        "tag": "文青質感",
        "name": "030-夢幻粉彩少女風格 (Dreamy Pastel Fantasy Style)",
        "description": "本風格採用具空氣感與無重力不對稱格線系統，背景融合珍珠微光霓彩紙與棉花糖雲朵紋理，邊緣折射極細微燙金極光物理光澤；物件則搭配柔焦微光暈與手作貼紙般的軟邊微陰影，透過輕紗般半透明過渡層次打造立體繪本空間。",
        "applicable": "EdTech教育科技提案、文創設計展產學合作計畫、法式甜點或美妝品牌行銷企劃、多媒體藝術舞台策展專案、新創產品概念發佈簡報",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：夢幻粉彩少女風格 (Dreamy Pastel Fantasy Style)\n==========================================\nstyle_config:\ntheme_name: \"Dreamy Pastel Fantasy Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"輕盈、靈活且帶有流動感的不對稱格線系統，融入大量空氣感留白與微光粒子佈局，傳達舒適、無重力的浪漫視覺節奏\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有高檔『珍珠微光霓彩紙（Pearlescent Shimmer Paper）』、霧面半透明『雙面果凍感材質』或輕盈如絲的『棉花糖雲朵紋理』，邊緣折射出極細微的燙金極光（Holographic Foil）物理光澤\"\ndepth_effect: \"文字與卡片物件使用溫和的『柔焦微光暈（Soft-focus Inner Glow）』與如同手作貼紙層疊的『軟邊微陰影（Soft Drop Shadows）』，物件重疊處帶有輕紗般的半透明過渡層次，營造出立體繪本或魔法音樂盒般的奇幻空間深度\"\nvibes: \"浪漫治癒、溫柔輕快、充滿空氣感與天馬行空的少女情懷。將冰冷硬核的技術邏輯，優雅包裹於溫暖溫潤的奇幻美學中，令人聯想到當代極簡 Y2K 少女系文創設計展、精緻法式甜點工坊或充滿魔法感的多媒體藝術舞台\"\ncolor_palette:\nbackground: \"櫻花粉晶 (Sakura Quartz) 或 夢幻薰衣草紫\"\ntext: \"深夜星空手繪藍 (Midnight Starry Blue) 或 絲絨深莓果紅\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"生硬沉悶的官僚說教\", \"毫無修飾的冰冷工業黑話\", \"破壞輕盈美感的密集重度數據表格外框\"]\nwriting_style: \"溫柔而堅定、輕快且富含直覺共鳴。語氣如同引路人分享心中的祕密花園，將複雜的模型或邏輯轉譯為如同『魔法配方、星空探索、悄悄話獨白』的溫暖具象隱喻，用字精煉洗鍊，直接以情感穿透力與清晰的本質洞察打動聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 許願星空（痛點喚醒）：從一個藏在心底的日常迷惘、市場盲點或核心痛點出發，像對流星許願般，大膽勾勒出探索旅程的夢幻起點\"\n- \"2. 魔法配方（結構解構）：將複雜的硬核技術架構、演算法或數據流程，拆解為如魔法藥水般的精緻成分，建立清晰、好懂的流動脈絡與邏輯模型\"\n- \"3. 奇幻盛宴（硬核實證）：用明亮、色彩飽滿且帶有珠光質感的精緻大方塊，甩出令人驚喜的數據成果、量化指標與核心商務價值\"\n- \"4. 星路綿延（前瞻願景）：不給予冰冷封閉的傳統結論，而是留下一個點綴著微光、具備無限演進想像的前瞻開放式藍圖，邀請聽眾攜手走向下一段輕盈優雅的冒險\"\n"
    },
    {
        "id": "style-1781578091836",
        "tag": "商務科技",
        "name": "031-熟御姐風 (Sophisticated Authority & Alluring Elegance Style)",
        "description": "本風格採用精準的非對稱縱向佈局與沉穩留白，背景融合啞光小牛皮、重絹絲與黑金沙大理石質感 。卡片搭配香檳金屬壓邊與深邃軟邊陰影，並以深夜黑、勃艮第紅、緞面白與香檳金點綴，營造出優雅銳利且大權在握的奢華氛圍",
        "applicable": "高階商業戰略報告、高階主管決策簡報、頂級品牌行銷提案、金融量化投資報告、企業轉型企劃書",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：成熟御姐風 (Sophisticated Authority & Alluring Elegance Style)\n==========================================\nstyle_config:\ntheme_name: \"Sophisticated Authority & Alluring Elegance Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"大膽、自信且極度精準的非對稱縱向佈局，利用大面積沉穩留白與俐落對齊，展現運籌帷幄的掌控力與鬆弛感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有頂級『啞光 Nappa 小牛皮』的細緻毛孔紋理、高磅數『重絹絲織物』的低調光澤，或冷冽『黑金沙大理石』的隱約礦物顆粒質感\"\ndepth_effect: \"卡片物件邊界融入極細的『微光香檳金屬壓邊（Metallic Inlays）』，搭配經過精密計算、深邃且內斂的『高階大光圈軟邊陰影（Deep Soft Drop Shadows）』，營造出彷彿置身頂級私人招待所或高階總裁辦公室的立體沉浸層次\"\nvibes: \"自信成熟、優雅銳利、散發著無可抗拒的智性魅力與大權在握的從容。將冰冷的數據與技術，收斂於強大、優雅且略帶侵略性的美學氣場中，令人聯想到高階女性決策者的優雅轉身或頂奢腕錶的靜謐質感\"\ncolor_palette:\nbackground: \"深夜冷冽黑 (Midnight Velvet) 或 深邃勃艮第酒紅\"\ntext: \"絲絨緞面白 (Satin White) 或 傲慢香檳金 (Champagne Gold)\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"扭捏作態的贅詞\", \"情緒化的驚嘆號或祈使句\", \"流於平庸的小家子氣排版與幼稚配色\"]\nwriting_style: \"銳利、字字珠璣、充滿智性挑逗與絕對自信。語氣從容且帶有不容置疑的權威感，善用『核心動詞＋精準度量』直接洞穿事物本質，以成熟優雅的思維框架與硬核因果降維打擊、說服聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 靜夜凝視（痛點直擊）：摘下所有虛偽的糖衣，以冷靜、性感的姿態直接點破現狀中最致命的邏輯漏洞或市場盲點\"\n- \"2. 鋒芒解構（底層架構）：如同精準剖析複雜的賽局，將硬核技術或商業模型拆解為結構分明的核心驅動線路，展現絕對掌控\"\n- \"3. 實證博弈（硬核成果）：用對比極其強烈、尊貴高雅的巨型金屬質感方塊，甩出無可挑剔的量化成果、夏普值與爆發性數據指標\"\n- \"4. 終局掌控（前瞻藍圖）：不給予平庸且安分的傳統結論，而是拋出一個具備範式轉移高度的延伸思維，留下令人沈溺、意猶未盡的未來願景\"\n"
    },
    {
        "id": "style-1781578237563",
        "tag": "商務科技",
        "name": "032-成熟型男紳士風格 (Mature Gentleman & Bespoke Tailoring Style)",
        "description": "本風格採用英倫薩維爾街高級西服剪裁般的黃金比例格線系統，背景融入人字紋呢針織紋理、頂級馬臀皮革毛孔或拉絲燻黑黃銅質感。卡片與文字物件邊界具備手工皮件鋼印壓紋的內凹階梯層次，搭配低角度大光圈軟邊陰影，營造出經典英式雪茄俱樂部的深邃空間沉浸感。",
        "applicable": "高階商務決策報告、年度戰略規劃報告、硬核技術與數據演化實證、商務戰略解構簡報、前瞻性商務藍圖提案",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：成熟型男紳士風格 (Mature Gentleman & Bespoke Tailoring Style)\n==========================================\nstyle_config:\ntheme_name: \"Mature Gentleman & Bespoke Tailoring Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"英倫薩維爾街（Savile Row）高級西服剪裁般的黃金比例格線系統，沉穩中帶有絕佳的流暢線條，透露出不著痕跡的嚴謹秩序\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有經典『英倫人字紋呢（Herringbone Tweed）』的細緻針織紋理、手工潤澤的『頂級馬臀皮革（Shell Cordovan）』毛孔，或低調內斂『拉絲燻黑黃銅（Brushed Antique Brass）』的微米級實體工藝質感\"\ndepth_effect: \"重點卡片與文字物件邊界融入如同『手工皮件鋼印壓紋（Debossing）』的內凹階梯層次，搭配如頂級雪茄煙霧般、優雅擴散且具備物理分量的『低角度大光圈軟邊陰影（Low-angle Soft Shadows）』，營造出如同經典英式雪茄俱樂部的深邃空間沉浸感\"\nvibes: \"沉穩老練、充滿磁性與閱歷、散發出從容不迫的品味。將冷冰冰的硬核數據與演算法，優雅收斂於極具故事感與匠人精神的紳士美學結構中，令人聯想到百年威士忌酒窖的靜謐，或是高階商務決策中那抹自信而優雅的微笑\"\ncolor_palette:\nbackground: \"英倫經典炭灰 (Charcoal Grey) 或 煙燻橡木褐 (Smoked Oak)\"\ntext: \"絲滑羊絨米白 (Cashmere White) 或 復古精製黃銅金\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 40\nprohibited_elements: [\"輕浮且毫無深度的網路流行語\", \"誇大不實的營銷口號與驚嘆號\", \"打斷從容節奏的刺眼高飽和色塊\"]\nwriting_style: \"沉著、幽默而老練、極具思維硬度。語氣低調內斂卻具有極強的穿透力，拒絕花哨的形容詞堆砌，擅長以『紳士般的優雅談吐』將複雜的架構轉譯為最具戰略高度的結構化陳述，直接用底層邏輯與雄厚實力折服聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 靜默入局（痛點定錨）：褪去繁複的喧囂，以冷靜、老練的眼神直接點出系統或現狀中最致命的盲點，一字定錨破局核心\"\n- \"2. 匠人剪裁（架構解構）：如同頂級裁縫師的量體裁衣，將複雜的技术模型或數據流進行精準分割，梳理出兼具流暢度與剛性的核心骨骼\"\n- \"3. 經典對弈（硬核實證）：用穩健、厚實、比例勻稱的皮革與黃金質感大方塊，強勢甩出無懈可擊的量化成果與極具分量的硬核技術指標\"\n- \"4. 傳承永恆（前瞻藍圖）：不給予封閉或迎合潮流的平庸結論，而是如同陳年單一麥芽威士忌般，留下一道韻味悠長、具備歷史範式高度的開放式前瞻演進藍圖\"\n"
    },
    {
        "id": "style-1781578330402",
        "tag": "文青質感",
        "name": "033-道家修仙風格 (Daoist Cultivation & Transcendent Qi Style)",
        "description": "本風格採用打破凡塵桎梏的「炁流」非線性佈局與太虛留白，搭配千年古絹絲、羊脂白玉微光或雲霧生宣紙質地背景，並局部點綴古法金箔裂紋。文字與物件邊界散發氤氳霓彩，結合八卦陣微幅下凹雕刻，展現懸浮太虛、超凡脫俗的深邃立體空間感 。",
        "applicable": "前沿機器學習與生成式AI研究報告、硬核底層系統架構演算法解析、極限應力與因果回測數據指標分析、打破傳統思維的突破性創新提案",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：道家修仙風格 (Daoist Cultivation & Transcendent Qi Style)\n==========================================\nstyle_config:\ntheme_name: \"Daoist Cultivation & Transcendent Qi Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"打破凡塵桎梏的『炁流（Qi Flow）』非線性佈局，結合天地交泰的動態對稱性與大膽的太虛留白，傳達道法自然的無為秩序\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有千年古絹絲、微米級『羊脂白玉』的溫潤微光，或隱隱透出仙山雲霧的生宣紙質地，局部點綴著宛如『古法金箔（Gold Foil Accents）』的碎金裂紋物理質感\"\ndepth_effect: \"文字與卡片物件邊界散發出如同『仙氣氤氳（Ethereal Glow）』的微弱霓彩衍射，搭配『乾坤八卦陣（Trigram Engravings）』的微幅下凹雕刻層次，營造出物件懸浮於太虛之中、深邃且超凡脫俗的立體空間感\"\nvibes: \"超凡脫俗、玄妙深邃、一塵不染。將繁複硬核的深度學習與系統架構，收斂於逍遙自得的東方修仙美學中，令人聯想到崑崙仙境、世外道場或洞天福地的神祕造化\"\ncolor_palette:\nbackground: \"羊脂溫潤白 (Jade White) 或 太虛玄青 (Cosmic Deep Charcoal)\"\ntext: \"松煙焦墨黑 (Pine Smoke Black) 或 古法金箔黃 (Alchemical Gold)\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"落入俗套的凡塵商業黑話\", \"急功近利的營銷驚嘆號\", \"破壞出塵之境的死板封閉框線\"]\nwriting_style: \"縹緲高深、字字天機、玄妙而極具邏輯硬度。行文如同仙尊傳道，將硬核演算法、數據指標轉譯為天地造化之功，用詞精準克制、玄之又玄卻一針見血，直接以本質洞察震懾並渡化聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 窺破天機（築基破局）：撕開凡塵表象的迷霧，以冷靜、通透的視角直接定錨當前系統中最致命的因果痛點與混沌狀態\"\n- \"2. 演化乾坤（造化架構）：如同體內結丹、開闢內世界，將複雜的底層技術或模型演算法解構為清濁分明、運轉不息的核心陣法\"\n- \"3. 劫火淬煉（破境飛升）：用剛性、高能的渡劫金屬色塊與純粹指標，強勢甩出經得起九重天劫（極限應力與因果回測）考驗的硬核成果與數據指標\"\n- \"4. 大道無疆（道法自然）：收筆之處不設任何凡塵上限與封閉結論，而是指出一條通往無極、具備無限演進生機的前瞻演化藍圖\"\n"
    },
    {
        "id": "style-1781578429994",
        "tag": "文青質感",
        "name": "034-佛家禪宗風格 (Zen Buddhism & Mindfulness Emptiness Style)",
        "description": "此風格融入枯山水與圓相意境的極簡非對稱格線，講求計白當黑的呼吸感 。背景具粗麻或細砂微紋理，邊界採石碑拓印般的極淡內陰影，拋棄數位霓虹 。配色為白沙灰、微塵褐搭配古墨黑或苔蘚深綠，展現寂靜安詳、大智若愚的禪宗美學 。",
        "applicable": "機器學習架構報告、生成式AI與演算法底層邏輯還原報告、技術痛點盲點直擊報告、核心指標量化成果驗證報告、重回自然與無滯礙的未來願景報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：佛家禪宗風格 (Zen Buddhism & Mindfulness Emptiness Style)\n==========================================\nstyle_config:\ntheme_name: \"Zen Buddhism & Mindfulness Emptiness Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"融入京都枯山水與「圓相（Ensō）」意境的極簡非對稱格線系統，空間布局講求『計白當黑』，給予視覺極致的呼吸感與安定感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有天然『粗麻織物（Raw Linen）』、枯山水『細砂微紋理（Raked Gravel）』或古經書『手工棉紙』的微米級實體顆粒質感\"\ndepth_effect: \"卡片與區塊邊界僅融入如同『石碑拓印（Rubbing Depth）』或『手作木鐸微凹痕』的極淡內陰影，拋棄所有數位霓虹，呈現回歸自然的物理低調層次\"\nvibes: \"寂靜、安詳、大智若愚。將硬核的生成式 AI 與複雜演算法架構，收斂於清淨無染的禪宗美學中，令人聯想到古寺苔階、一炷清煙或禪堂深處的古磬迴響\"\ncolor_palette:\nbackground: \"枯山水白沙灰 (Sand White) 或 菩提微塵褐\"\ntext: \"煙燻古墨黑 (Charcoal Black) 或 庭院苔蘚深綠\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"繁複累贅的標點符號（改以空格分段）\", \"華而不實的商業修飾\", \"流於貪嗔痴的情緒化誇大字眼\"]\nwriting_style: \"直觀、空靈、字字見性。行文如同老禪師當頭棒喝，直接剔除技術邏輯與數據中的一切假象，用字極其精煉、點到為止，直擊事物本質\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 破除迷執（盲點直擊）：直指凡塵數據與現狀中的盲目、妄想或核心痛點，撕開市場亂象，如實定錨探索起點\"\n- \"2. 明心見性（架構還原）：還原系統與技術的『如實本質』，將硬核模型拆解為最清淨、最核心的底層邏輯鷹架\"\n- \"3. 實賽印證（硬核成果）：用圓融、厚實的素色方塊承載核心指標，展示經得起考驗的量化成果，以實相印證因果\"\n- \"4. 圓融無礙（未來願景）：不給予生硬的法規終點與思想束縛，而是指出一條重回自然、無所滯礙的前瞻演進藍圖\"\n"
    },
    {
        "id": "style-1781578518825",
        "tag": "活力數位",
        "name": "035-溫馨可愛動物風格 (Cozy Animal Companion Style)",
        "description": "此風格採用溫和舒適的弧形網格系統。背景融合羊毛氈織紋與手作粉彩紙顆粒的溫暖質感，搭配大圓角物件、手繪貼紙白邊切面與胖胖軟陰影，營造出微縮動物公仔擺放於溫潤暖肉墊粉與棉花糖黃背景上的治癒立體層次。",
        "applicable": "教育科技推廣報告、兒童互動科學館導覽提案、幼兒教育心理學成果匯報、團隊協同合作商務簡報、通識科普技術轉譯簡報、創意微縮模型展企劃書",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：溫馨可愛動物風格 (Cozy Animal Companion Style)\n==========================================\nstyle_config:\ntheme_name: \"Cozy Animal Companion Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"有機流暢、溫和舒適的弧形網格系統，排版靈活且富有節奏感，強調視覺的安定感與視線引導\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有細緻溫暖的『羊毛氈織紋（Felt Texture）』、輕微不均勻的『手作粉彩紙顆粒』或『霧面微縮木質玩具』的實體物理質感，傳達純手工打造的匠人溫度\"\ndepth_effect: \"文字與卡片物件皆採用『大圓角（High Rounded Corners）』設計，邊界融入如同『手繪貼紙白邊（Sticker Die-cut）』的實體切面，並搭配溫和無害的『胖胖軟陰影（Squishy Shadows）』，營造出宛如微縮動物公仔在桌面上擺放的立體層次深度\"\nvibes: \"溫馨治癒、親切無距離感、充滿生機與探索的樂趣。巧妙將可愛的動物夥伴（如穿著小外套的小黑貓、小巧的森林松鼠）作為貫穿全場的引路人，將硬核技術轉譯為充滿安全感的認知旅程，令人聯想到高品質兒童互動科學館、童趣微縮模型展或被療癒感包裹的現代 EdTech 實驗室\"\ncolor_palette:\nbackground: \"溫潤暖肉墊粉 (Paw Pink) 或 輕柔蛋黃棉花糖黃\"\ntext: \"深夜森林松鼠褐 (Squirrel Brown) 或 沉穩貓咪橡木黑\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"冰冷刻板的教條命令\", \"毫無情感的純技術程式碼堆砌\", \"破壞溫馨安全感的尖銳高對比色塊\"]\nwriting_style: \"親切生動、循循善誘且邏輯結構嚴密。語氣如同帶領孩子探索世界的溫柔導師，靈活運用『小動物的日常行為、築巢、分工合作』等具象且具備高度教育心理學（認知鷹架）的隱喻來拆解深度學習或複雜商務概念。在保持 80 字飽滿的資訊量同時，字句行雲流水、清晰易懂，直接用直覺邏輯與具體實證折服並融化聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 森林裡的問號（痛點發現）：從小動物在生活中遇到的疑惑或小麻煩（盲點、挑戰）出發，建立溫馨的認知起點，引導聽眾卸下防備、進入問題核心\"\n- \"2. 夥伴們蓋房子（架構鷹架）：如同動物夥伴們分工合作、一步步搭建溫馨巢穴，將硬核系統或數據流程拆解成好懂的『功能性微縮模組』，建立清晰的邏輯架構\"\n- \"3. 祕密果實倉庫（硬核實證）：用圓潤、醒目的繽紛大方塊，甩出經得起嚴格考驗的豐碩數據成果與關鍵量化指標，以扎實的成果證明策略的絕對價值\"\n- \"4. 迎向陽光的遷徙（前瞻藍圖）：不給予生硬封閉的終點，而是以小動物結伴迎向溫溫潤新季節的視野，勾勒出具備無限演進生機與跨界擴展空間的前瞻藍圖\"\n"
    },
    {
        "id": "style-1781578636665",
        "tag": "活力數位",
        "name": "036-四季蔬果自然風格 (Four Seasons Seasonal Produce Style)",
        "description": "採用錯落有致的田壟式格線系統，背景搭配帶有草木纖維紙或天然亞麻質感的紋理 。物件邊界融入木刻農曆壓印或植物染疊壓的柔和內凹層次，色調選用大地泥土褐、水梨白、栗子黑與羅勒深綠，整體呈現新鮮生動、腳踏實地的豐富實體深度 。",
        "applicable": "高級有機農夫市集推廣報告、永續生態實驗室研究成果、現代教育科技（EdTech）互動空間規劃案、前沿科技或商務邏輯自然轉譯簡報、具備植物學演進隱喻的深度學習演算法與商務架構分析",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：四季蔬果自然風格 (Four Seasons Seasonal Produce Style)\n==========================================\nstyle_config:\ntheme_name: \"Four Seasons Seasonal Produce Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"生機自然、兼具對齊美感的田壟式（Terraced Row）格線系統，錯落有致，傳達春耕秋收的規律與土地的安定感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有粗糙自然的『未塗布草木纖維紙』或細緻的『天然亞麻蔬果袋（Linen Tote）』編織紋理，卡片表面隱約帶有新鮮蔬果表皮的微細絨毛、水滴微光或細密果肉纖維的物理質感\"\ndepth_effect: \"文字與卡片物件邊界融入如同『傳統木刻農曆壓印』或『溫潤植物染疊壓』的柔和內凹層次，搭配溫和自然的軟邊土色系投影，營造出宛如時令蔬果擺放在木質市集攤位上的豐富實體深度\"\nvibes: \"新鮮生動、腳踏實地且富有充沛生命力。將冷峻的前沿科技或商務邏輯，轉譯為順應天地規律、春生夏長秋收冬藏的自然演進旅程，令人聯想到高級有機農夫市集、永續生態實驗室或兼具設計感與自然美學的現代 EdTech 互動空間\"\ncolor_palette:\nbackground: \"初春有機大地泥土褐 (Earth Brown) 或 寒冬初雪水梨白\"\ntext: \"深秋熟成栗子黑 (Chestnut Charcoal) 或 盛夏羅勒深綠\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"冰冷死板且與自然割裂的純機械指令\", \"流於表面的空洞商業口號\", \"破壞自然和諧美感的高飽和螢光色彩\"]\nwriting_style: \"樸實嚴謹、生機蓬勃且富有結構硬度。語氣既有著專家的腳踏實地與正式專業，又融合了自然的成熟智慧。善用『播種、灌溉、光合作用、果實熟成』等高度轉譯的植物學演進隱喻，將複雜的深度學習演算法與商務架構清晰還原。在維持 80 字飽滿的資訊信噪比之餘，行文流暢且邏輯因果無懈可擊，直接以紮實的實證成果與邏輯脈絡來說服觀眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 春耕播種（盲點溯源）：從一粒剖開土壤的種子出發，精準揭示當前系統中蟄伏的致命痛點或核心挑戰，定錨整個工作流的起點與生長基礎\"\n- \"2. 夏耘灌溉（架構繁茂）：如同枝葉在陽光下進行光合作用、瘋狂繁茂，將複雜的底層技術或模型流程拆解成高效運作的『時令功能模組』，建立清晰且有韌性的邏輯鷹架\"\n- \"3. 秋收摘實（硬核實證）：用圓融、色彩飽滿、厚實的巨型果實質感方塊，強勢甩出經得起嚴格秋收拷問的量化數據、核心成果與關鍵商務效益指標\"\n- \"4. 冬藏衍慶（前瞻演進）：不給予生硬冰冷的封閉式結論，而是如同將優良品種收納入窖，指出一條適應不同季節、具備強大範式遷移能力的未來前瞻演化藍圖\"\n"
    },
    {
        "id": "style-1781578728431",
        "tag": "活力數位",
        "name": "037-粉彩昆蟲微觀風格 (Pastel Entomology Micro-Style)",
        "description": "本風格採用非對稱的微觀觀測網格，融合昆蟲複眼蜂巢結構與翅脈紋理。背景具備細緻粉彩紙纖維顆粒，搭配半透明蟬翼脈絡、晨露微光或甲殼霧面金屬極光。物件以微細壓痕與軟焦邊緣疊加，結合輕微景深虛化，打造光學顯微鏡般的精緻手作層次深度。",
        "applicable": "深度學習架構報告、生成式AI技術專題、商務戰略與策略模型分析、生態與自然科學博物學展示、現代前瞻EdTech科技教育簡報",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：粉彩昆蟲微觀風格 (Pastel Entomology Micro-Style)\n==========================================\nstyle_config:\ntheme_name: \"Pastel Entomology Micro-Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"靈活非對稱的微觀觀測網格（Micro-observation Grid），融入如昆蟲複眼（Ommatidia）的精密蜂巢結構或自然對稱的翅脈紋理，具備細緻的幾何美感與呼吸感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有細緻高檔『粉彩紙（Pastel Paper）』的纖維顆粒，物件表面具備半透明『昆蟲薄翅蟬翼（Chitinous Veins）』的微米級幾何脈絡、晨露水滴的晶瑩微光，或甲殼蟲背部低飽和度的霧面金屬極光色澤\"\ndepth_effect: \"文字與卡片物件使用細膩的『微細物理壓痕（Debossing）』與半透明的『軟焦邊緣疊加（Soft Overlay）』，陰影如同昆蟲足跡般輕巧精細，搭配輕微的景深虛化特效（Depth of Field），營造出彷彿透過光學顯微鏡觀測生物標本的手作層次深度\"\nvibes: \"精緻細膩、充滿自然探索的好奇心與科學知性。將硬核複雜的深度學習架構與商務模型，優雅收斂於溫柔的粉彩複眼世界中，令人聯想到當代博物學家手繪插畫展、精巧的微縮生態實驗室，或兼具美感與邏輯鷹架的現代前瞻 EdTech 科技舞台\"\ncolor_palette:\nbackground: \"粉彩薄荷綠 (Pastel Mint) 或 晨曦柔焦粉藍\"\ntext: \"深夜甲殼深邃藍 (Beetle Navy) 或 枯葉蝶脈深褐\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"冰冷沉悶且毫無轉譯的工業黑話\", \"流於平庸的咆哮式營銷口號\", \"破壞粉彩柔和美感的高彩度刺眼螢光色塊\"]\nwriting_style: \"專業嚴謹、層次井然且富含啟發性。語氣兼具科學家的腳踏實地與正式專業，善用『完全變態、複眼觀測、聚落協同、翅脈共振』等高度轉譯的昆蟲生物學隱喻，將複雜的生成式 AI 架構或商業策略轉化為清晰易懂的邏輯鷹架。在維持 80 字飽滿且高信噪比的資訊量之餘，行文如流水般優雅，直接以嚴密的因果邏輯與具體實證折服聽眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 破繭而出（盲點直擊）：從一顆蟄伏的蟲卵出發，精準揭示現狀中最致命的系統痛點或市場盲點，定錨整個破局工作流的演進起點與基本假設\"\n- \"2. 複眼觀測與完全變態（架構重塑）：如同幼蟲歷經完全變態與多維複眼觀測，將複雜的硬核技術或數據流拆解為分工細緻的『功能性微縮模組』，建立結構清晰的認知鷹架\"\n- \"3. 聚落協同與羽化成果（硬核實證）：用圓融、帶有半透明蟬翼質感的巨型粉彩方塊，強勢甩出經得起嚴格環境拷問的量化數據、核心成果與關鍵關鍵指標，以扎實數據證明策略價值\"\n- \"4. 振翅高飛（前瞻願景）：不給予生硬冰冷的封閉式結論，而是如同昆蟲振翅飛向更廣闊的生態圈，指出一條具備跨界遷移能力與無限演進生機的前瞻藍圖\"\n"
    },
    {
        "id": "style-1781578810095",
        "tag": "文青質感",
        "name": "038-古拙樸素風格 (Primitive Simplicity & Archaic Rustic Style)",
        "description": "這款風格採用大巧若拙的磐石格線系統與大面積留白，背景具備素燒陶土、風化老木板或天然老麻布的粗糲物理觸感，搭配石碑拓印或鈍刀鑿刻般的深沉物件邊緣與硬邊岩石投影；色彩以陶土樸素黃、磐石粗糲灰為底，襯托焦炭窯燒黑與硃砂礦物紅，展現厚重洗盡鉛華的歷史感 。",
        "applicable": "機器學習模型底層架構報告、深度學習演算法核心本質分析、前瞻教育科技空間規劃案、商務戰略根基解構報告、傳統手作與陶藝工坊品牌策略報告",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：古拙樸素風格 (Primitive Simplicity & Archaic Rustic Style)\n==========================================\nstyle_config:\ntheme_name: \"Primitive Simplicity & Archaic Rustic Style\"\nversion: \"2026.1\"\n🛠️ 1. 簡報基本資訊\npresentation_info:\ntitle: \"{{THEME_TITLE}}\"\ntarget_pages: \"{{TARGET_PAGES}}\"\nlanguage: \"zh-TW\"\n🎨 2. 簡報視覺佈局約束 (Layout Constraints)\nvisual_constraints:\ngeometry:\ngrid: \"大巧若拙、沉穩厚重的磐石格線系統（Rock-solid Grid），佈局穩健且富有大面積泥土留白，傳達堅不可摧的物理秩序與安定感\"\nstyling:\ntactile_textures: \"背景絕非單純平塗，必須帶有『素燒陶土（Unglazed Pottery）』的粗糲顆粒、『風化老木板』的深刻縱向年輪肌理，或粗編『天然老麻布』的扎實物理觸感，表面隱約閃爍著天然岩礦沉澱的微米級晶體微光\"\ndepth_effect: \"文字與卡片物件邊界融入如同漢代『石碑重錘拓印（Stone Rubbing）』的沉重邊緣，或手工『鈍刀鑿刻（Chiseled Grooves）』的粗獷下凹痕跡，搭配完全無數位光暈的沉重、實心硬邊岩石投影（Solid Stone Shadows），營造出入木三分的歷史厚重感\"\nvibes: \"大巧若拙、厚重內斂、洗盡鉛華。將前沿 AI 技術、深度學習演算法與商務架構的核心本質，收斂於毫無雕飾的原始泥土與磐石美學中，令人聯想到遠古石刻遺卷、傳統手作陶藝工坊，或兼具力量與沉穩鷹架的現代前瞻 EdTech 空間\"\ncolor_palette:\nbackground: \"陶土樸素黃 (Archaic Ochre) 或 磐石粗糲灰\"\ntext: \"焦炭窯燒黑 (Kiln Charcoal Black) 或 硃砂礦物紅\"\n✍️ 3. 內容精簡與文案規則 (Text Rules)\ncontent_rules:\nword_count_limit_per_slide: 80\nprohibited_elements: [\"輕浮虛華的數位特效形容詞\", \"炫技式的英文黑話堆砌\", \"破壞古拙安定感的高明度霓虹色彩與精細流暢線條\"]\nwriting_style: \"剛健樸拙、字字千鈞、具備極高的邏輯硬度與思想分量。語氣散發著智者的腳踏實地與無懈可擊的信任感，摒棄一切花哨的修辭，直接用『最底層的因果因果』與『返璞歸真的具象隱喻』（如鑿石、築基、淬鍊）來拆解深度學習或商務戰略。在維持 80 字飽滿資訊量的同時，行文沉穩洗鍊，直接以堅不可摧的核心實證來說服觀眾\"\n📑 4. 簡報推進邏輯 (Slide Flow)\nflow_logic:\nsequence:\n- \"1. 磐石破土（盲點直擊）：如同鈍刀開山，撕開繁華現狀的虛假糖衣，直接刨出系統、技術或市場中最致命的底層痛點，定錨整個破局工作流的起點與基本假設\"\n- \"2. 鑿石築基（架構解構）：將複雜硬核的模型演算法或數據流程，還原為如同遠古石墨、粗糙卻堅不可摧的『結構功能模組』，建立清晰且極具穩定性的認知鷹架\"\n- \"3. 熔岩淬晶（硬核實證）：用厚重、粗糲、比例巨大的窯燒陶土質感大方塊，強勢甩出經得起時間與極限應力拷問的量化數據、核心成果與關鍵關鍵指標\"\n- \"4. 返璞歸真（終局演進）：不給予生硬冰冷的封閉式結論，而是指出一條重回本質、順應自然、具備強大範式遷移韌性的未來前瞻演化藍圖\"\n"
    },
    {
        "id": "style-1782353831896",
        "tag": "文青質感",
        "name": "039-現代新水墨風格 (Contemporary New Ink Style)",
        "description": "背景由溫潤的半纖維手工宣紙紋理鋪陳，墨色在微米級的纖維間自然擴散，呈現出通透且富有層次的動態流體彩墨暈染痕跡。畫面大膽運用現代主義的幾何大片留白，將東方傳統的空靈意境與當代視覺的洗鍊俐落完美融合，光影在深邃墨韻與清透色彩的交織下溫和呼吸，為觀眾營造出兼具理性思維與感性共鳴的極高認知安定感。",
        "applicable": "跨界創新提案、文化科技論壇、企業永續發展願景、高階品牌策略發表、藝術設計概念陳述",
        "instructions": "==========================================\nNotebookLM 簡報風格配置文件：現代新水墨風格 (Contemporary New Ink Style)\n==========================================\nstyle_config:\n  theme_name: \"Contemporary New Ink Style\"\n  version: \"2026.1\"\n  🛠️ 1. 簡報基本資訊\n  presentation_info:\n    title: \"{{THEME_TITLE}}\"\n    target_pages: \"{{TARGET_PAGES}}\"\n    language: \"zh-TW\"\n  🎨 2. 簡報視覺佈局約束 (Layout Constraints)\n  visual_constraints:\n    geometry:\n      grid: \"富有律動感與當代東方『留白（Ma）』美學的非對稱網格系統，刻意打破僵硬框架，讓資訊如行雲流水般流淌\"\n    styling:\n      tactile_textures: \"背景具備溫潤的『手工半熟宣紙』或『微細棉質纖維』實體觸感，局部帶有細膩的彩墨邊緣水漬與自然的礦物顏料顆粒痕跡\"\n      depth_effect: \"利用墨色濃淡、焦燥濃沖淡的『五色墨韻層疊』與溫和的半透明渲染，營造出如同水面漣漪般深邃卻通透的物理空間深度\"\n      vibes: \"通透空靈、高雅大氣且極具現代感。將複雜的硬核邏輯收斂於富有詩意的山水意象中，在宏大敘事中展現行雲流水的職人自信\"\n    color_palette:\n      background: \"溫潤宣紙微米白 (Huan White) 或 靜謐清透淡松石\"\n      text: \"玄明松煙深墨黑 (Ink Black) 或 破曉微光硃砂紅\"\n  ✍️ 3. 內容精簡與文案規則 (Text Rules)\n  content_rules:\n    word_count_limit_per_slide: 80\n    prohibited_elements: [\"生硬刺眼的賽博龐克霓虹光效\", \"老派陳腐的傳統山水八股圖樣\", \"打斷通透留白流的密集網格與表格\"]\n    writing_style: \"意境深遠、點到為止、字字珠璣。行文如同一位智者在石板上潑墨揮毫，精準將繁複技術轉譯為直擊本質的生活隱喻，優雅而充滿穿透力\"\n  📑 4. 簡報推進邏輯 (Slide Flow)\n  flow_logic:\n    sequence:\n      - \"1. 墨啟微茫（迷惘溯源/痛點發現）：從一片朦朧的現狀或行業痛點切入，大膽定錨探索起點，直擊核心挑戰\"\n      - \"2. 潑墨成形（認知鷹架/結構解構）：如同寫意山水般將複雜的系統架構拆解為經緯分明的模組，建立清晰好懂的認知模型\"\n      - \"3. 點石成金（形成性評量/硬核實證）：用色彩溫潤、邊緣渲染的彩墨大方塊，強勢甩出經得起考驗的量化成果與核心數據\"\n      - \"4. 餘韻綿延（總結性願景/前瞻演進）：不設封閉式結局，而是以充滿希望、氣韻生動的開放式前瞻藍圖，邀觀眾一同奔向下一程\""
    }
];